surface_mapper:
  class: SurfaceMapper

  use_prior: True
  prior_resolution: 2.0 # [m]
  prior_sigma_height: 0.25 # [m]
  prior_density: 0.25 # [m]
  prior_color: [0.2, 0.2, 0.2] # [r, g, b]
  prior_max_dist: 2.0 # [m]

  min_iterations: 100
  num_viewpoints: 1
  max_time: 10 # [s]
  min_time: 0.5 # [s]

  max_distance: 100.0 # [m]

  mapping:
    every_keyframe: 1 # do mapping every X keyframes
    final_refine_iters: 25000 # iterations of final refinement
    eval_before_final_ba: False
    move_points: True # apply transformation on Gaussians to account for loop closure and BA
    BA: False # Bundle Adjustment during 3DGS mapping - not fully implemented, but kept for reference
    pcd_downsample: 32 # downsamples the unprojected depth map --> point cloud
    pcd_downsample_init: 16 # first frame downsampling factor is smaller
    adaptive_pointsize: True
    point_size: 0.05
    camera_extent: 6.0
    lambda_invalid_depth: 10.0
    pcd_depth_trunc: 20 # [m]
    background_color: [0, 0, 0]
    calibration:
      distorted: False
  Training:
    init_lr: 6.0
    ssim_loss: False # use SSIM in mapping (online and refinement)
    alpha: 0.80 # weight (between 0 and 1) of the rgb loss compared to depth loss
    init_itr_num: 1050
    init_gaussian_update: 100
    init_gaussian_reset: 500
    init_gaussian_th: 0.005
    init_gaussian_extent: 30
    mapping_itr_num: 60
    gaussian_update_every: 150 # we prune and densify once every 150 iterations.
    gaussian_update_offset: 50
    gaussian_th: 0.7 # used in densify and prune - minimum opacity to be kept
    gaussian_extent: 1.0 # used in densify and prune. We prune points with larger 3d scale than 0.1 * gaussian_extent
    gaussian_reset: 2001
    size_threshold: 20 # used in densify and prune. We prune points that have a larger radius than 20 in screen space
    window_size: 10
    pose_window: 5
    edge_threshold: 4
    rgb_boundary_threshold: 0.01
    kf_translation: 0.04
    kf_min_translation: 0.02
    kf_overlap: 0.95
    prune_mode: 'slam'
    sh_degree: 3
    lr:
      cam_rot_delta: 0.003
      cam_trans_delta: 0.001
  opt_params:
    iterations: 30000
    init_lr: 6.0
    position_lr_init: 0.00016
    position_lr_final: 0.0000016
    position_lr_delay_mult: 0.01
    position_lr_max_steps: 30000
    feature_lr: 0.0025  # default 0.0025
    opacity_lr: 0.05
    scaling_lr: 0.001
    rotation_lr: 0.001
    percent_dense: 0.01
    lambda_dssim: 0.2
    densification_interval: 100
    opacity_reset_interval: 3000
    densify_from_iter: 500
    densify_until_iter: 15000
    densify_grad_threshold: 0.0002
  pipeline_params:
    convert_SHs_python: False
    compute_cov3D_python: False

  viser:
    port: 7007
    update_time: 2.0
    max_surface_points: 1000
    max_rock_points: 100
