import pylupnt as pnt
import numpy as np
import pytest


def test_constants():
    assert hasattr(pnt, "PI")
    assert hasattr(pnt, "TWO_PI")
    assert hasattr(pnt, "PI_OVER_TWO")
    assert hasattr(pnt, "E")
    assert hasattr(pnt, "EPS")
    assert hasattr(pnt, "RAD")
    assert hasattr(pnt, "DEG")
    assert hasattr(pnt, "ARCSEC_DEG")
    assert hasattr(pnt, "DEG_ARCSEC")
    assert hasattr(pnt, "RAD_ARCSEC")
    assert hasattr(pnt, "ARCSEC_RAD")
    assert hasattr(pnt, "INCH_M")
    assert hasattr(pnt, "FOOT_M")
    assert hasattr(pnt, "MILE_M")
    assert hasattr(pnt, "KM_M")
    assert hasattr(pnt, "M_KM")
    assert hasattr(pnt, "SECS_DAY")
    assert hasattr(pnt, "SECS_HOUR")
    assert hasattr(pnt, "SECS_MINUTE")
    assert hasattr(pnt, "MINS_HOUR")
    assert hasattr(pnt, "MINS_DAY")
    assert hasattr(pnt, "HOURS_DAY")
    assert hasattr(pnt, "DAYS_WEEK")
    assert hasattr(pnt, "DAYS_YEAR")
    assert hasattr(pnt, "DAYS_CENTURY")
    assert hasattr(pnt, "DAYS_SEC")
    assert hasattr(pnt, "JD_MJD_OFFSET")
    assert hasattr(pnt, "TT_TAI_OFFSET")
    assert hasattr(pnt, "A1_TAI_OFFSET")
    assert hasattr(pnt, "JD_CCSDS_TAI")
    assert hasattr(pnt, "JD_J2000_TT")
    assert hasattr(pnt, "MJD_CCSDS_TAI")
    assert hasattr(pnt, "MJD_J2000_TT")
    assert hasattr(pnt, "MJD_COORDINATE_TAI")
    assert hasattr(pnt, "MJD_COORDINATE_TT_TCG_TCB")
    assert hasattr(pnt, "L_B")
    assert hasattr(pnt, "L_G")
    assert hasattr(pnt, "GM_SUN")
    assert hasattr(pnt, "GM_MERCURY")
    assert hasattr(pnt, "GM_VENUS")
    assert hasattr(pnt, "GM_EARTH")
    assert hasattr(pnt, "GM_MOON")
    assert hasattr(pnt, "GM_MARS_SYSTEM")
    assert hasattr(pnt, "GM_JUPITER_SYSTEM")
    assert hasattr(pnt, "GM_SATURN_SYSTEM")
    assert hasattr(pnt, "GM_URANUS_SYSTEM")
    assert hasattr(pnt, "GM_NEPTUNE_SYSTEM")
    assert hasattr(pnt, "GM_PLUTO_SYSTEM")
    assert hasattr(pnt, "GM_CERES")
    assert hasattr(pnt, "GM_VESTA")
    assert hasattr(pnt, "D_EARTH_MOON")
    assert hasattr(pnt, "D_EARTH_EMB")
    assert hasattr(pnt, "R_MOON")
    assert hasattr(pnt, "R_EARTH")
    assert hasattr(pnt, "OMEGA_EARTH_MOON")
    assert hasattr(pnt, "D_MOON_EMB")
    assert hasattr(pnt, "AU")
    assert hasattr(pnt, "C")
