C
	SUBROUTINE ROTATE_Z(ANGLE,X_INIT,X_TRANS)
C
	REAL X_INIT(3),X_TRANS(3)
C
	X_TRANS(1)=X_INIT(1)*COS(ANGLE)+X_INIT(2)*SIN(ANGLE)
	X_TRANS(2)=X_INIT(2)*COS(ANGLE)-X_INIT(1)*SIN(ANGLE)
	X_TRANS(3)=X_INIT(3)
C
	RETURN
	END
