# Light
light:
  intensity: 100000.0
  attenuation_radius: 1000.0 # [cm]
  inner_cone_angle: 0.0 # [deg]
  outer_cone_angle: 60.0 # [deg]
  temperature: 6500.0 # [kelvin]
  light_color: [1.0, 1.0, 1.0] # RGB, 0-1 range

# Camera
camera:
  # Intrinsics
  projection_type: "perspective"
  fov: 60.0 # [deg]
  width: 1024 # [px]
  height: 728 # [px]

  # Properties
  ortho_width: 100.0 # [cm]

  enable_motion_blur: false
  motion_blur_amount: 0.0

  enable_bloom: false
  bloom_intensity: 0.0

  depth_of_field_focal_distance: 0.0
  depth_of_field_fstop: 0.0

  scene_fringe_intensity: 0.0
  ambient_occlusion_intensity: 0.0
  auto_exposure_bias: 0.0
  vignette_intensity: 0.0
  lens_flare_intensity: 0.0

# Rover **********************************************************************
rover:
  ue_class: opportunity_rover

  enable_lights: ["front"]
  enable_cameras: ["front_left", "front_right", "left_left", "left_right", "right_left", "right_right", "back_left", "back_right"]

  # Lights
  lights:
      front:
        inherit_from: light
        xyz: [0.5, 0.0, 0.5] # [m]
        rpy: [0.0, 0.0, 0.0] # [deg]

      left:
        inherit_from: light
        xyz: [0.0, 0.5, 0.5] # [m]
        rpy: [0.0, 0.0, 90.0] # [deg]

      right:
        inherit_from: light
        xyz: [0.0, -0.5, 0.5] # [m]
        rpy: [0.0, 0.0, -90.0] # [deg]

      back:
        inherit_from: light
        xyz: [-0.5, 0, 0.5] # [m]
        rpy: [0.0, 0.0, 180.0] # [deg]

  cameras:
      # Front
      front_left:
        inherit_from: camera
        xyz: [0.5, 0.1, 1.4] # [m]
        rpy: [0.0, 0.0, 0.0] # [deg]

      front_right:
        inherit_from: camera
        xyz: [0.5, -0.1, 1.4] # [m]
        rpy: [0.0, 0.0, 0.0] # [deg]

      # Left
      left_left:
        inherit_from: camera
        xyz: [0.4, 0.25, 1.4] # [m]
        rpy: [0.0, 0.0, 90.0] # [deg]

      left_right:
        inherit_from: camera
        xyz: [0.6, 0.25, 1.4] # [m]
        rpy: [0.0, 0.0, 90.0] # [deg]

      # Right
      right_left:
        inherit_from: camera
        xyz: [0.4, -0.25, 1.4] # [m]
        rpy: [0.0, 0.0, -90.0] # [deg]

      right_right:
        inherit_from: camera
        xyz: [0.6, -0.25, 1.4] # [m]
        rpy: [0.0, 0.0, -90.0] # [deg]

      # Back
      back_left:
        inherit_from: camera
        xyz: [0.25, 0.1, 1.4] # [m]
        rpy: [0.0, 0.0, 180.0] # [deg]

      back_right:
        inherit_from: camera
        xyz: [0.25, -0.25, 1.4] # [m]
        rpy: [0.0, 0.0, 180.0] # [deg]

# Lander **********************************************************************
lander:
  ue_class: blue_moon_lander

  enable_apriltags: []

  # Apriltags
  apriltags:
    front:
      xyz: [3.6, 0.0, 1.0] # [m]
      rpy: [0.0, 0.0, 0.0] # [deg]
      scale: 1.0 # [m]
      apriltag_id: 0

    left:
      xyz: [0.0, 3.6, 1.0] # [m]
      rpy: [0.0, 0.0, 90.0] # [deg]
      scale: 1.0 # [m]
      apriltag_id: 0

    right:
      xyz: [0.0, -3.6, 1.0] # [m]
      rpy: [0.0, 0.0, -90.0] # [deg]
      scale: 1.0 # [m]
      apriltag_id: 0

    back:
      xyz: [-3.6, 0.0, 1.0] # [m]
      rpy: [0.0, 0.0, 180.0] # [deg]
      scale: 1.0 # [m]
      apriltag_id: 0
