segmentation:
  class: UnetPlusPlus
  checkpoint: ./pretrained/segmentation/Unreal_UnetPlusPlus_20251014.pth
  # class: PAN
  # checkpoint: ./pretrained/segmentation/Unreal_PAN_20251014.pth

  encoder_name: tu-resnet18
  encoder_weights: imagenet
  in_channels: 3
  classes: 7
  input_size: [512, 512]
