#!/usr/bin/env python3
"""Generate GMAT R2026a force-model reference vectors for cross-validating LuPNT.

Companion to `gen_gmat_reference.py` (kept separate so the original R2022a
kepler/J2/frame fixture is untouched). This one targets the force models added
to the cross-validation suite -- higher-order spherical-harmonic gravity,
third-body point-mass perturbation, and solar radiation pressure -- and it uses
the **latest GMAT (R2026a)** pointed at LuPNT's own **DE440** ephemeris (GMAT
ships only up to DE424), so the third-body and SRP geometries use the same Sun
and Moon positions LuPNT does.

Every case is propagation-based: GMAT reports spacecraft states, not
accelerations, so unlike the Orekit force-model checks (which are formula-level)
these compare a propagated Cartesian state after a fixed arc. LuPNT's constants
and gravity coefficients are forced onto GMAT (Earth.Mu / .EquatorialRadius,
Luna.Mu, Sun.Mu, and the shared EGM96 `.cof`) so a residual is an algorithm /
integrator / frame-realisation difference, never an adopted-constant one.

Usage (from the repo root; only the Python standard library is used):

    GMAT_CONSOLE=/path/to/GMAT/R2026a/bin/GmatConsole-R2026a \\
        pixi run python cpp/test/gmat/gen_gmat_forces_reference.py

Writes `cpp/test/gmat/data/gmat_forces_reference.json` and, for documentation,
`cpp/test/gmat/data/gmat_forces_reference.script` (machine paths tokenised).
Consumed by `test_force_models_gmat.cc`.
"""

from __future__ import annotations

import json
import os
import subprocess
import sys
import tempfile
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parent))
from gen_gmat_reference import (  # noqa: E402  reuse the console finder + parser
    GMAT_SUCCESS_MARKER,
    find_gmat_console,
    parse_report_blocks,
    report_file,
)

REPO = Path(__file__).resolve().parents[3]
OUTPUT_PATH = Path(__file__).resolve().parent / "data" / "gmat_forces_reference.json"
SCRIPT_DOC_PATH = Path(__file__).resolve().parent / "data" / "gmat_forces_reference.script"

# LuPNT constants (cpp/lupnt/core/constants.h), km-based where GMAT wants km.
GM_EARTH = 398600.435507  # [km^3/s^2]
R_EARTH = 6378.137  # [km]
GM_SUN = 132712440041.279419  # [km^3/s^2]
GM_MOON = 4902.800118  # [km^3/s^2]
SOLAR_FLUX = 1361.0  # [W/m^2], LuPNT SOLAR_FLUX_AU

DE440 = os.environ.get(
    "LUPNT_DE440",
    str(REPO / "data" / "LuPNT_data" / "ephemeris" / "de440.bsp"),
)
EGM96_COF = str(REPO / "data" / "LuPNT_data" / "gravity" / "earth" / "EGM96.cof")

GRAVITY_NM = 8  # degree/order of the Earth field compared

# Initial state (EarthMJ2000Eq, km / km/s) for the gravity and third-body
# cases: MEO-ish, moderately inclined and eccentric.
CART0_KM = [
    -78.74054921709086,
    6614.247029719887,
    3375.314830789883,
    -5.820053437151488,
    -2.093123025519158,
    3.993752615196549,
]
# SRP uses its OWN high, sunward orbit so the satellite is continuously
# sunlit -- LuPNT's apparent-disk penumbra and GMAT's shadow model differ, and
# a MEO orbit is eclipsed for part of the arc, which would swamp the cannonball
# comparison. At the 2024-03-15 epoch the Sun is near the +X GCRF axis, so a
# high +X/+Z state stays out of Earth's anti-Sun shadow.
SRP_CART0_KM = [42000.0, 3000.0, 25000.0, -0.6, 3.05, 0.35]
# Report states after these elapsed-second marks.
DTS = [1800.0, 3600.0, 7200.0]

# Spacecraft ballistic properties for SRP (cannonball).
SRP_CR = 1.5
SRP_AREA = 4.0  # [m^2]
SRP_MASS = 500.0  # [kg]


def cart_sat(name: str, r: list[float]) -> str:
    return f"""Create Spacecraft {name};
GMAT {name}.DateFormat = UTCGregorian;
GMAT {name}.Epoch = '15 Mar 2024 12:00:00.000';
GMAT {name}.CoordinateSystem = EarthMJ2000Eq;
GMAT {name}.DisplayStateType = Cartesian;
GMAT {name}.X = {r[0]!r};
GMAT {name}.Y = {r[1]!r};
GMAT {name}.Z = {r[2]!r};
GMAT {name}.VX = {r[3]!r};
GMAT {name}.VY = {r[4]!r};
GMAT {name}.VZ = {r[5]!r};
GMAT {name}.SRPArea = {SRP_AREA!r};
GMAT {name}.Cr = {SRP_CR!r};
GMAT {name}.DryMass = {SRP_MASS!r};
"""


def params(sat: str) -> str:
    return " ".join(f"{sat}.EarthMJ2000Eq.{c}" for c in ("X", "Y", "Z", "VX", "VY", "VZ"))


def build_script(rf_paths: dict[str, str]) -> str:
    s = []
    s.append("% GMAT R2026a force-model reference for LuPNT cross-validation.\n")
    s.append("% Generated by cpp/test/gmat/gen_gmat_forces_reference.py.\n\n")

    # DE440 via SPICE + LuPNT constants forced onto GMAT.
    s.append(f"GMAT SolarSystem.EphemerisSource = 'SPICE';\n")
    s.append(f"GMAT SolarSystem.SPKFilename = '{DE440}';\n")
    s.append(f"GMAT Earth.Mu = {GM_EARTH!r};\n")
    s.append(f"GMAT Earth.EquatorialRadius = {R_EARTH!r};\n")
    s.append(f"GMAT Luna.Mu = {GM_MOON!r};\n")
    s.append(f"GMAT Sun.Mu = {GM_SUN!r};\n\n")

    # Spacecraft: one per force model (each propagated separately).
    for name, r0 in (("GravSat", CART0_KM), ("TbSat", CART0_KM), ("SrpSat", SRP_CART0_KM)):
        s.append(cart_sat(name, r0))
        s.append("\n")

    # --- Force models ---
    s.append(
        f"""Create ForceModel GravFM;
GMAT GravFM.CentralBody = Earth;
GMAT GravFM.PrimaryBodies = {{Earth}};
GMAT GravFM.Drag.AtmosphereModel = None;
GMAT GravFM.SRP = Off;
GMAT GravFM.GravityField.Earth.Degree = {GRAVITY_NM};
GMAT GravFM.GravityField.Earth.Order = {GRAVITY_NM};
GMAT GravFM.GravityField.Earth.PotentialFile = '{EGM96_COF}';

Create ForceModel TbFM;
GMAT TbFM.CentralBody = Earth;
GMAT TbFM.PointMasses = {{Earth, Sun, Luna}};
GMAT TbFM.Drag.AtmosphereModel = None;
GMAT TbFM.SRP = Off;

Create ForceModel SrpFM;
GMAT SrpFM.CentralBody = Earth;
GMAT SrpFM.PointMasses = {{Earth}};
GMAT SrpFM.Drag.AtmosphereModel = None;
GMAT SrpFM.SRP = On;
GMAT SrpFM.SRP.Flux = {SOLAR_FLUX!r};
GMAT SrpFM.SRP.SRPModel = Spherical;

"""
    )
    for fm in ("GravFM", "TbFM", "SrpFM"):
        prop = fm.replace("FM", "Prop")
        s.append(
            f"""Create Propagator {prop};
GMAT {prop}.FM = {fm};
GMAT {prop}.Type = RungeKutta89;
GMAT {prop}.InitialStepSize = 30;
GMAT {prop}.Accuracy = 1e-13;
GMAT {prop}.MinStep = 0;
GMAT {prop}.MaxStep = 300;

"""
        )

    for name, path in rf_paths.items():
        s.append(report_file(name, path))
        s.append("\n")

    # --- Mission sequence: one Propagate per spacecraft per segment ---
    s.append("BeginMissionSequence;\n")
    plan = [
        ("GravSat", "GravProp", "rfGrav"),
        ("TbSat", "TbProp", "rfTb"),
        ("SrpSat", "SrpProp", "rfSrp"),
    ]
    for sat, prop, rf in plan:
        s.append(f"Report {rf} {params(sat)};\n")  # initial state
        prev = 0.0
        for dt in DTS:
            seg = dt - prev
            prev = dt
            s.append(f"Propagate {prop}({sat}) {{{sat}.ElapsedSecs = {seg!r}}};\n")
            s.append(f"Report {rf} {params(sat)};\n")
    return "".join(s)


def read_cart(blk: dict) -> list[float]:
    # Report params are Sat.EarthMJ2000Eq.{X..VZ}; parse_report_blocks keys them
    # by the bare component after the last dot is not guaranteed, so match suffix.
    out = []
    for c in ("X", "Y", "Z", "VX", "VY", "VZ"):
        key = next(k for k in blk if k.endswith("." + c) or k == c)
        out.append(blk[key] * 1e3)  # km -> m
    return out


def main() -> None:
    console = find_gmat_console()
    print(f"Using GmatConsole: {console}")
    if not Path(DE440).exists():
        sys.exit(f"DE440 not found at {DE440}; set LUPNT_DE440 or fetch LuPNT_data.")

    rf_names = ["rfGrav", "rfTb", "rfSrp"]
    with tempfile.TemporaryDirectory() as td:
        tmp = Path(td)
        rf_paths = {n: str(tmp / f"{n}.txt") for n in rf_names}
        script = build_script(rf_paths)
        script_path = tmp / "forces.script"
        script_path.write_text(script)

        # Documentation copy with machine paths tokenised.
        doc = script.replace(DE440, "<DE440.bsp>").replace(EGM96_COF, "<EGM96.cof>")
        for n in rf_names:
            doc = doc.replace(rf_paths[n], f"<{n}.txt>")
        SCRIPT_DOC_PATH.write_text(doc)

        env = dict(os.environ)
        lib = console.parent.parent / "lib"
        env["LD_LIBRARY_PATH"] = f"{lib}:{console.parent}:" + env.get("LD_LIBRARY_PATH", "")
        res = subprocess.run(
            [str(console), "-r", str(script_path)],
            capture_output=True,
            text=True,
            cwd=str(console.parent),
            timeout=600,
        )
        if GMAT_SUCCESS_MARKER not in res.stdout and "Report" not in res.stdout:
            # GMAT prints per-report success sparsely; rely on report files existing.
            pass
        if any(err in res.stdout for err in ("**** ERROR ****", "Exception")):
            print(res.stdout[-2000:])
            sys.exit("GMAT reported an error; see output above.")

        blocks = {n: parse_report_blocks(Path(rf_paths[n])) for n in rf_names}

    def section(rf: str) -> list:
        blks = blocks[rf]
        cases = [
            {
                "cart0": read_cart(blks[0]),
                "propagated": [{"dt": dt, "cart": read_cart(b)} for dt, b in zip(DTS, blks[1:])],
            }
        ]
        return cases

    out = {
        "_meta": {
            "description": "GMAT R2026a force-model reference (gravity 8x8, third-body, SRP).",
            "generator": "cpp/test/gmat/gen_gmat_forces_reference.py",
            "gmat_version": "R2026a",
            "ephemeris": "DE440 (LuPNT's, via SPICE)",
            "constants": {
                "GM_EARTH": GM_EARTH * 1e9,
                "R_EARTH": R_EARTH * 1e3,
                "GM_SUN": GM_SUN * 1e9,
                "GM_MOON": GM_MOON * 1e9,
                "solar_flux": SOLAR_FLUX,
            },
        },
        "gravity_propagation": {
            "cof_file": "EGM96.cof",
            "n_max": GRAVITY_NM,
            "m_max": GRAVITY_NM,
            "cases": section("rfGrav"),
        },
        "third_body_propagation": {
            "perturbers": ["SUN", "MOON"],
            "GM_sun": GM_SUN * 1e9,
            "GM_moon": GM_MOON * 1e9,
            "cases": section("rfTb"),
        },
        "srp_propagation": {
            "Cr": SRP_CR,
            "area": SRP_AREA,
            "mass": SRP_MASS,
            "solar_flux": SOLAR_FLUX,
            "cases": section("rfSrp"),
        },
    }
    OUTPUT_PATH.write_text(json.dumps(out, indent=2) + "\n")
    print(f"Wrote {OUTPUT_PATH}")


if __name__ == "__main__":
    main()
