gsplat_mapper:
  class: GsplatMapper
  max_depth: 200.0 # [m]
  voxel_size: 0.05 # [m]
  scene_scale: 1e2 # [m]
  res_prior: 0.1

  seed: 49
  batch_size: 5
  cam_weights: "uniform" # [uniform, balanced, latest, linear, exponential]

  birdseye_cameras:
    - front_left

  viser_port: 8080
  viser_update_every: 10000
  viewer_update_every: 10000

  background_color: white
  warmup_length: 10000
  refine_every: 10000
  cull_alpha_thresh: 1e-3
  cull_scale_thresh: 1e9
  cull_screen_size: 1e9
  reset_alpha_every: 1e9
  use_scale_regularization: true
  num_downscales: 0
  sh_degree: 0

  # Loss
  lambda_depth: 1.0
  lambda_full: 1.0
  lambda_empty: 1.0
  lambda_scale_reg: 1.0

  # Optimizers
  eps: 1.0e-15
  optimizers:
    means:
      optimizer:
        lr: 1.6e-4
      scheduler:
        lr_final: 1.6e-6
        max_steps: 30000
    features_dc:
      optimizer:
        lr: 2.5e-3
    features_rest:
      optimizer:
        lr: 1.25e-4
    opacities:
      optimizer:
        lr: 0.05
    scales:
      optimizer:
        lr: 0.005
    quats:
      optimizer:
        lr: 0.001
    camera_opt:
      optimizer:
        lr: 1.0e-4
      scheduler:
        lr_final: 5.0e-7
        max_steps: 30000
        warmup_steps: 1000
        lr_pre_warmup: 0
    bilateral_grid:
      optimizer:
        lr: 2.0e-3
      scheduler:
        lr_final: 1.0e-4
        max_steps: 30000
        warmup_steps: 1000
        lr_pre_warmup: 0
