#!/usr/bin/env bash
# Build the LuPNT manual (latex_docs/lupnt.tex) -> build/lupnt.pdf
#
# No system LaTeX installation is required: `pixi exec` fetches tectonic into a
# throwaway environment, so nothing is added to pixi.toml or the lockfile.
# Tectonic runs BibTeX itself, so refs.bib needs no separate pass -- but it must
# sit beside lupnt.tex, which is why it is committed here rather than generated.
#
# Usage:
#   ./build.sh              # full build into ./build
#   ./build.sh --keep       # keep intermediates (.aux/.bbl) for debugging
#
# If tectonic is already on PATH it is used directly; otherwise pixi provides it.

set -euo pipefail

cd "$(dirname "$0")"

OUTDIR="build"
mkdir -p "$OUTDIR"

# --- resolve where the heavy figures live ----------------------------------
# This directory is text only. Generated/large artefacts live under
# $LUPNT_DATA_PATH/docs, which is fetched rather than committed. Resolve it
# from the environment (pixi activation sets it), then .env, then the default
# in-tree location, and hand the answer to LaTeX through figpath.tex.
REPO_ROOT="$(cd .. && pwd)"
DATA_PATH="${LUPNT_DATA_PATH:-}"
if [[ -z "$DATA_PATH" && -f "$REPO_ROOT/.env" ]]; then
  DATA_PATH="$(sed -n 's/^LUPNT_DATA_PATH=//p' "$REPO_ROOT/.env" | tail -1)"
fi
DATA_PATH="${DATA_PATH:-$REPO_ROOT/data/LuPNT_data}"
FIGDIR="$DATA_PATH/docs"

# A trailing slash is required: LaTeX concatenates \datafigdir with the filename.
printf '%% Generated by build.sh -- do not commit.\n\\providecommand{\\datafigdir}{%s/}\n' \
  "$FIGDIR" > figpath.tex

# The title-page logo is derived from the committed SVG in assets/. LaTeX
# cannot read SVG, so render it to PDF once, into the data directory (this
# tree stays text-only). Failure is non-fatal: \datafig degrades to a
# placeholder rather than breaking the build.
LOGO_SVG="$REPO_ROOT/assets/lupnt_logo_horizontal.svg"
LOGO_PDF="$FIGDIR/lupnt_logo_horizontal.pdf"
if [[ -f "$LOGO_SVG" && ! -f "$LOGO_PDF" ]]; then
  mkdir -p "$FIGDIR"
  echo "==> rendering title-page logo -> $LOGO_PDF"
  if command -v rsvg-convert >/dev/null 2>&1; then
    rsvg-convert -f pdf -o "$LOGO_PDF" "$LOGO_SVG" || true
  elif command -v pixi >/dev/null 2>&1; then
    pixi exec --spec librsvg rsvg-convert -f pdf -o "$LOGO_PDF" "$LOGO_SVG" 2>/dev/null || true
  fi
  [[ -f "$LOGO_PDF" ]] || echo "    (could not render the logo; title page will show a placeholder)" >&2
fi

if [[ -d "$FIGDIR" ]]; then
  echo "==> figures: $FIGDIR"
else
  echo "==> figures: $FIGDIR (missing -- those figures will render as placeholders)" >&2
  echo "    regenerate tutorial figures with: pixi run python latex_docs/scripts/extract_notebook_figures.py" >&2
fi

if command -v tectonic >/dev/null 2>&1; then
  RUNNER=(tectonic)
elif command -v pixi >/dev/null 2>&1; then
  RUNNER=(pixi exec --spec tectonic tectonic)
else
  echo "error: neither tectonic nor pixi found on PATH." >&2
  echo "       install one, or compile manually with:" >&2
  echo "         pdflatex lupnt && bibtex lupnt && pdflatex lupnt && pdflatex lupnt" >&2
  exit 1
fi

echo "==> building lupnt.pdf with: ${RUNNER[*]}"
"${RUNNER[@]}" --outdir "$OUTDIR" lupnt.tex

if [[ "${1:-}" != "--keep" ]]; then
  rm -f "$OUTDIR"/*.aux "$OUTDIR"/*.log "$OUTDIR"/*.out "$OUTDIR"/*.toc \
        "$OUTDIR"/*.bbl "$OUTDIR"/*.blg "$OUTDIR"/*.bcf 2>/dev/null || true
fi

echo "==> $OUTDIR/lupnt.pdf"
