application:
  class: MappingApp
  segmentation: segmentation.yaml
  stereo_depth: depth.yaml::raft_stereo

ekf:
  class: ExtendedKalmanFilter
  dynamics: dynamics.yaml::dynamics2d
  Q: [0.1, 0.1, 0.01]
  R: [0.1, 0.1, 0.01]
  state: [0.0, 0.0, 0.0]
  P: [0.1, 0.1, 0.01]
