cameras:
  front_left:
    H: 360 # [px] Image height
    W: 640 # [px] Image width
    fovx: 1.2217304763960306 # [rad]
    body_T_cam: # [m]
      - [1.0, 0.0, 0.0, 0.25]
      - [0.0, 1.0, 0.0, +0.1]
      - [0.0, 0.0, 1.0, 0.0]
      - [0.0, 0.0, 0.0, 1.0]
    save: true
    enabled: true

  front_right:
    H: 360 # [px] Image height
    W: 640 # [px] Image width
    fovx: 1.2217304763960306 # [rad]
    body_T_cam: # [m]
      - [1.0, 0.0, 0.0, 0.25]
      - [0.0, 1.0, 0.0, -0.1]
      - [0.0, 0.0, 1.0, 0.0]
      - [0.0, 0.0, 0.0, 1.0]
    save: true
    enabled: true

  left:
    H: 360 # [px] Image height
    W: 640 # [px] Image width
    fovx: 1.2217304763960306 # [rad]
    body_T_cam: # [m]
      - [0.0, -1.0, 0.0, 0.0]
      - [1.0, 0.0, 0.0, 0.25]
      - [0.0, 0.0, 1.0, 0.0]
      - [0.0, 0.0, 0.0, 1.0]
    save: true
    enabled: true

  right:
    H: 360 # [px] Image height
    W: 640 # [px] Image width
    fovx: 1.2217304763960306 # [rad]
    body_T_cam: # [m]
      - [0.0, 1.0, 0.0, 0.0]
      - [-1.0, 0.0, 0.0, 0.25]
      - [0.0, 0.0, 1.0, 0.0]
      - [0.0, 0.0, 0.0, 1.0]
    save: true
    enabled: true

  back_left:
    H: 360 # [px] Image height
    W: 640 # [px] Image width
    fovx: 1.2217304763960306 # [rad]
    body_T_cam: # [m]
      - [-1.0, 0.0, 0.0, -0.25]
      - [0.0, -1.0, 0.0, +0.1]
      - [0.0, 0.0, 1.0, 0.0]
      - [0.0, 0.0, 0.0, 1.0]
    save: true
    enabled: true

  back_right:
    H: 360 # [px] Image height
    W: 640 # [px] Image width
    fovx: 1.2217304763960306 # [rad]
    body_T_cam: # [m]
      - [1.0, 0.0, 0.0, -0.25]
      - [0.0, 1.0, 0.0, +0.1]
      - [0.0, 0.0, 1.0, 0.0]
      - [0.0, 0.0, 0.0, 1.0]
    save: true
    enabled: true
