simulation:
  seed: 0
  tf: 120.0 # [s]
  output:
    dir: output/progress_update
    add_timestamp: false
  realtime: false

  agents:
    rover:
      class: RoverAgent
      environment: open3d_environment.yaml::open3d_small

      timestep: 1.0 # [s] Update rate
      radius: 0.5 # [m] Body radius
      initial_state: [25.0, -3.0, 3.14] # [m, m, rad]

      cameras:
        Front:
          res: [640, 360] # [px]
          fovx: 1.2217304763960306 # [rad]
          body_T_cam:
            - [1.0, 0.0, 0.0, 0.0]
            - [0.0, 1.0, 0.0, 0.0]
            - [0.0, 0.0, 1.0, 0.0]
            - [0.0, 0.0, 0.0, 1.0]
          save: true
          enabled: true

      dynamics:
        class: Dynamics2D

      application:
        class: MappingApp

        cameras:
          - Front

        path_planner:
          class: PathPlanner
          goal: [-20.0, -15.0] # [m]
          # xlims: [-35.0, 35.0] # [m]
          # ylims: [-15.0, 15.0] # [m]
          xlims: [-30, 30] # [m]
          ylims: [-20, 20] # [m]

          d_keep_out: 2.0 # [m]
          max_slope: 90.0 # [deg]
          lambda_slope: 1.0
          resolution: 0.2 # [m]
          max_deviation: 0.5 # [m]

          filter_size: 3.0
          threshold_factor: 4.0
          dist_local_map: 10.0  # [m]
          fov_local_map: 75.0  # [deg]
          dist_keep_out: 1.5 # [m]
          min_points: 100

          dist_no_buffer: 0.5 # [m]

        controller:
          class: Controller2D
          v_max: 0.5 # [m/s]
          w_max: 0.5 # [rad/s]

        tracker:
          class: GroundTruthTracker

        mapper: gaussian_mapper.yaml
