import collections.abc
import numpy
import numpy.typing
import typing
from typing import Any, ClassVar, overload

A1_TAI_OFFSET: float
ARCSEC_DEG: float
ARCSEC_RAD: float
AU: float
BEIDOU: GnssConst
C: float
CM_M: float
C_PLASMA: float
DAYS_CENTURY: float
DAYS_SEC: float
DAYS_WEEK: float
DAYS_YEAR: float
DEG: float
DEG2RAD_PLASMA: float
DEG_ARCSEC: float
DEIMOS: BodyId
D_EARTH_EMB: float
D_EARTH_MOON: float
D_MOON_EMB: float
E: float
E1: GnssFreq
E5: GnssFreq
E5a: GnssFreq
E5b: GnssFreq
E6: GnssFreq
EARTH: BodyId
EARTH_MOON_BARYCENTER: BodyId
ECEF: Frame
ECI: Frame
EMB: BodyId
EME: Frame
EMR: Frame
EPS: float
FOOT_M: float
GALILEO: GnssConst
GCRF: Frame
GLONASS: GnssConst
GM_CERES: float
GM_EARTH: float
GM_EARTH_PLASMA: float
GM_JUPITER_SYSTEM: float
GM_MARS_SYSTEM: float
GM_MERCURY: float
GM_MOON: float
GM_NEPTUNE_SYSTEM: float
GM_PLUTO_SYSTEM: float
GM_SATURN_SYSTEM: float
GM_SUN: float
GM_URANUS_SYSTEM: float
GM_VENUS: float
GM_VESTA: float
GPS: GnssConst
GSE: Frame
HOURS_DAY: float
ICRF: Frame
INCH_M: float
ITRF: Frame
JD_CCSDS_TAI: float
JD_J2000_TT: float
JD_MJD_OFFSET: float
JD_TDB: Time
JD_TT: Time
JUPITER: BodyId
JUPITER_BARYCENTER: BodyId
KILOGRAM: float
KILOMETER: float
KM_M: float
KM_MM: float
KM_S_KG_UNITS: UnitSystem
L1: GnssFreq
L2: GnssFreq
L5: GnssFreq
LT: Time
L_B: float
L_G: float
L_L: float
MARS: BodyId
MARS_BARYCENTER: BodyId
MARS_FIXED: Frame
MERCURY: BodyId
MERCURY_BARYCENTER: BodyId
METER: float
MILE_M: float
MINS_DAY: float
MINS_HOUR: float
MJD_CCSDS_TAI: float
MJD_COORDINATE_TAI: float
MJD_COORDINATE_TT_TCG_TCB: float
MJD_J2000_TT: float
MM_KM: float
MM_M: float
MOD: Frame
MOON: BodyId
MOON_CI: Frame
MOON_ME: Frame
MOON_OP: Frame
MOON_PA: Frame
M_CM: float
M_KM: float
M_MM: float
M_S_KG_UNITS: UnitSystem
NEPTUNE_BARYCENTER: BodyId
OMEGA_EARTH_MOON: float
PD45: IntegratorType
PHOBOS: BodyId
PI: float
PI_OVER_TWO: float
PI_PLASMA: float
PLASMA_BASE_PATH: str
PLUTO_BARYCENTER: BodyId
QZSS: GnssConst
RAD: float
RAD2DEG_PLASMA: float
RAD_ARCSEC: float
RE_PLASMA: float
RK4: IntegratorType
RK8: IntegratorType
RKF45: IntegratorType
R_EARTH: float
R_MOON: float
SATURN_BARYCENTER: BodyId
SECOND: float
SECS_DAY: float
SECS_DAY_PLASMA: float
SECS_HOUR: float
SECS_MINUTE: float
SER: Frame
SI_UNITS: UnitSystem
SOLAR_SYSTEM_BARYCENTER: BodyId
SSB: BodyId
SUN: BodyId
TAI: Time
TCB: Time
TCG: Time
TCL: Time
TDB: Time
TECU_PLASMA: float
TL: CoordinateScale
TOD: Frame
TT: Time
TT_TAI_OFFSET: float
TWO_PI: float
URANUS_BARYCENTER: BodyId
UT1: Time
UTC: Time
VENUS: BodyId
VENUS_BARYCENTER: BodyId
VENUS_FIXED: Frame
freq_L1: float
freq_L2: float
freq_L5: float

class AnalyticalOrbitDynamics(Dynamics):
    def __init__(self, *args, **kwargs) -> None: ...

class Antenna:
    def __init__(self, arg0: str) -> None: ...
    @overload
    def compute_gain(self, theta: Real, phi: Real) -> Real: ...
    @overload
    def compute_gain(
        self, theta: typing.Annotated[numpy.typing.ArrayLike, Real, "[m, 1]"], phi: Real
    ) -> typing.Annotated[numpy.typing.NDArray[Real], "[m, 1]"]: ...
    @overload
    def compute_gain(
        self, theta: Real, phi: typing.Annotated[numpy.typing.ArrayLike, Real, "[m, 1]"]
    ) -> typing.Annotated[numpy.typing.NDArray[Real], "[m, 1]"]: ...
    @overload
    def compute_gain(
        self,
        theta: typing.Annotated[numpy.typing.ArrayLike, Real, "[m, 1]"],
        phi: typing.Annotated[numpy.typing.ArrayLike, Real, "[m, 1]"],
    ) -> typing.Annotated[numpy.typing.NDArray[Real], "[m, 1]"]: ...
    def get_gain_matrix(
        self,
    ) -> typing.Annotated[numpy.typing.NDArray[numpy.float64], "[m, n]"]: ...
    def get_phi_vector(self) -> typing.Annotated[numpy.typing.NDArray[numpy.float64], "[m, 1]"]: ...
    def get_theta_vector(
        self,
    ) -> typing.Annotated[numpy.typing.NDArray[numpy.float64], "[m, 1]"]: ...
    @property
    def name(self) -> str: ...

class AntexLoader:
    @overload
    def __init__(self) -> None: ...
    @overload
    def __init__(self, filepath: str) -> None: ...
    @staticmethod
    def apply_pco_correction_ecef(
        t_tai: Real,
        pos_sp3_ecef: typing.Annotated[numpy.typing.ArrayLike, numpy.float64, "[3, 1]"],
        pco_neu_m: typing.Annotated[numpy.typing.ArrayLike, numpy.float64, "[3, 1]"],
    ) -> typing.Annotated[numpy.typing.NDArray[numpy.float64], "[3, 1]"]: ...
    @staticmethod
    def compute_ijk_to_ecef_rotation(
        t_tai: Real, r_sat_ecef: typing.Annotated[numpy.typing.ArrayLike, numpy.float64, "[3, 1]"]
    ) -> typing.Annotated[numpy.typing.NDArray[numpy.float64], "[3, 3]"]: ...
    def get_available_freq_codes(
        self, gnss_const: GnssConst, prn: typing.SupportsInt | typing.SupportsIndex, t_tai: Real
    ) -> list[str]: ...
    @overload
    def get_pco(
        self,
        gnss_const: GnssConst,
        prn: typing.SupportsInt | typing.SupportsIndex,
        freq: GnssFreq,
        t_tai: Real,
    ) -> typing.Annotated[numpy.typing.NDArray[numpy.float64], "[3, 1]"]: ...
    @overload
    def get_pco(
        self,
        gnss_letter: str,
        prn: typing.SupportsInt | typing.SupportsIndex,
        antex_freq_code: str,
        t_tai: Real,
    ) -> typing.Annotated[numpy.typing.NDArray[numpy.float64], "[3, 1]"]: ...
    @staticmethod
    def gnss_letter(gnss_const: GnssConst) -> str: ...
    def has_satellite(
        self, gnss_const: GnssConst, prn: typing.SupportsInt | typing.SupportsIndex
    ) -> bool: ...
    def load_file(self, filepath: str) -> None: ...
    @staticmethod
    def sat_id(gnss_const: GnssConst, prn: typing.SupportsInt | typing.SupportsIndex) -> str: ...

class Body:
    def __init__(self) -> None: ...
    @overload
    @staticmethod
    def Earth(
        n: typing.SupportsInt | typing.SupportsIndex = ...,
        m: typing.SupportsInt | typing.SupportsIndex = ...,
        gravity_file: str = ...,
    ) -> Body: ...
    @overload
    @staticmethod
    def Earth(
        units: UnitSystem,
        n: typing.SupportsInt | typing.SupportsIndex = ...,
        m: typing.SupportsInt | typing.SupportsIndex = ...,
        gravity_file: str = ...,
    ) -> Body: ...
    @overload
    @staticmethod
    def Jupiter() -> Body: ...
    @overload
    @staticmethod
    def Jupiter(units: UnitSystem) -> Body: ...
    @overload
    @staticmethod
    def Mars(
        n: typing.SupportsInt | typing.SupportsIndex = ...,
        m: typing.SupportsInt | typing.SupportsIndex = ...,
        gravity_file: str = ...,
    ) -> Body: ...
    @overload
    @staticmethod
    def Mars(
        units: UnitSystem,
        n: typing.SupportsInt | typing.SupportsIndex = ...,
        m: typing.SupportsInt | typing.SupportsIndex = ...,
        gravity_file: str = ...,
    ) -> Body: ...
    @overload
    @staticmethod
    def Moon(
        n: typing.SupportsInt | typing.SupportsIndex = ...,
        m: typing.SupportsInt | typing.SupportsIndex = ...,
        gravity_file: str = ...,
    ) -> Body: ...
    @overload
    @staticmethod
    def Moon(
        units: UnitSystem,
        n: typing.SupportsInt | typing.SupportsIndex = ...,
        m: typing.SupportsInt | typing.SupportsIndex = ...,
        gravity_file: str = ...,
    ) -> Body: ...
    @overload
    @staticmethod
    def Saturn() -> Body: ...
    @overload
    @staticmethod
    def Saturn(units: UnitSystem) -> Body: ...
    @overload
    @staticmethod
    def Sun() -> Body: ...
    @overload
    @staticmethod
    def Sun(units: UnitSystem) -> Body: ...
    @overload
    @staticmethod
    def Venus(
        n: typing.SupportsInt | typing.SupportsIndex = ...,
        m: typing.SupportsInt | typing.SupportsIndex = ...,
        gravity_file: str = ...,
    ) -> Body: ...
    @overload
    @staticmethod
    def Venus(
        units: UnitSystem,
        n: typing.SupportsInt | typing.SupportsIndex = ...,
        m: typing.SupportsInt | typing.SupportsIndex = ...,
        gravity_file: str = ...,
    ) -> Body: ...
    @property
    def GM(self) -> Real: ...
    @property
    def R(self) -> Real: ...
    @property
    def fixed_frame(self) -> Frame: ...
    @property
    def gravity_field(self): ...
    @property
    def id(self) -> BodyId: ...
    @property
    def inertial_frame(self) -> Frame: ...
    @property
    def name(self) -> str: ...
    @property
    def units(self) -> UnitSystem: ...
    @property
    def use_gravity_field(self) -> bool: ...

class BodyId:
    __members__: ClassVar[dict] = ...  # read-only
    DEIMOS: ClassVar[BodyId] = ...
    EARTH: ClassVar[BodyId] = ...
    EARTH_MOON_BARYCENTER: ClassVar[BodyId] = ...
    EMB: ClassVar[BodyId] = ...
    JUPITER: ClassVar[BodyId] = ...
    JUPITER_BARYCENTER: ClassVar[BodyId] = ...
    MARS: ClassVar[BodyId] = ...
    MARS_BARYCENTER: ClassVar[BodyId] = ...
    MERCURY: ClassVar[BodyId] = ...
    MERCURY_BARYCENTER: ClassVar[BodyId] = ...
    MOON: ClassVar[BodyId] = ...
    NEPTUNE_BARYCENTER: ClassVar[BodyId] = ...
    PHOBOS: ClassVar[BodyId] = ...
    PLUTO_BARYCENTER: ClassVar[BodyId] = ...
    SATURN_BARYCENTER: ClassVar[BodyId] = ...
    SOLAR_SYSTEM_BARYCENTER: ClassVar[BodyId] = ...
    SSB: ClassVar[BodyId] = ...
    SUN: ClassVar[BodyId] = ...
    URANUS_BARYCENTER: ClassVar[BodyId] = ...
    VENUS: ClassVar[BodyId] = ...
    VENUS_BARYCENTER: ClassVar[BodyId] = ...
    __entries: ClassVar[dict] = ...
    def __init__(self, value: typing.SupportsInt | typing.SupportsIndex) -> None: ...
    def __eq__(self, other: object) -> bool: ...
    def __hash__(self) -> int: ...
    def __index__(self) -> int: ...
    def __int__(self) -> int: ...
    def __ne__(self, other: object) -> bool: ...
    @property
    def name(self) -> str: ...
    @property
    def value(self) -> int: ...

class CartesianTwoBodyDynamics(NumericalOrbitDynamics):
    def __init__(self, GM: typing.SupportsFloat | typing.SupportsIndex) -> None: ...

class Config:
    @overload
    def __init__(self) -> None: ...
    @overload
    def __init__(self, arg0: dict) -> None: ...
    @overload
    def __init__(self, arg0: dict) -> None: ...
    def copy(self) -> Config: ...
    def get(self, key: str, default: object = ...) -> object: ...
    def items(self) -> list: ...
    def keys(self) -> list: ...
    def to_dict(self) -> dict: ...
    def to_string(self) -> str: ...
    def update(self, arg0: dict) -> None: ...
    def values(self) -> list: ...
    def __contains__(self, arg0: str) -> bool: ...
    def __copy__(self) -> Config: ...
    def __deepcopy__(self, memo: dict) -> Config: ...
    def __getattr__(self, arg0: str) -> object: ...
    def __getitem__(self, arg0: str) -> object: ...
    def __len__(self) -> int: ...
    def __setitem__(self, arg0: str, arg1: object) -> None: ...

class CoordinateScale:
    __members__: ClassVar[dict] = ...  # read-only
    TCB: ClassVar[CoordinateScale] = ...
    TCG: ClassVar[CoordinateScale] = ...
    TCL: ClassVar[CoordinateScale] = ...
    TDB: ClassVar[CoordinateScale] = ...
    TL: ClassVar[CoordinateScale] = ...
    TT: ClassVar[CoordinateScale] = ...
    __entries: ClassVar[dict] = ...
    def __init__(self, value: typing.SupportsInt | typing.SupportsIndex) -> None: ...
    def __eq__(self, other: object) -> bool: ...
    def __hash__(self) -> int: ...
    def __index__(self) -> int: ...
    def __int__(self) -> int: ...
    def __ne__(self, other: object) -> bool: ...
    @property
    def name(self) -> str: ...
    @property
    def value(self) -> int: ...

class DateTime:
    doy: int
    hour: int
    min: int
    sec: float
    year: int
    def __init__(
        self,
        year: typing.SupportsInt | typing.SupportsIndex,
        doy: typing.SupportsInt | typing.SupportsIndex,
        hour: typing.SupportsInt | typing.SupportsIndex,
        min: typing.SupportsInt | typing.SupportsIndex,
        sec: typing.SupportsFloat | typing.SupportsIndex,
    ) -> None: ...

class Dynamics:
    def __init__(self, *args, **kwargs) -> None: ...
    @overload
    def propagate(
        self,
        x0: typing.Annotated[numpy.typing.ArrayLike, Real, "[m, 1]"],
        t0: Real,
        tf: Real,
        u: typing.Annotated[numpy.typing.ArrayLike, Real, "[m, 1]"] = ...,
    ) -> typing.Annotated[numpy.typing.NDArray[Real], "[m, 1]"]: ...
    @overload
    def propagate(
        self,
        x0: typing.Annotated[numpy.typing.ArrayLike, Real, "[m, 1]"],
        t0: Real,
        tf: Real,
        u: typing.Annotated[numpy.typing.ArrayLike, Real, "[m, 1]"],
        stm: bool,
    ) -> object: ...
    @overload
    def propagate(
        self,
        x0: typing.Annotated[numpy.typing.ArrayLike, Real, "[m, 1]"],
        tfs: typing.Annotated[numpy.typing.ArrayLike, Real, "[m, 1]"],
    ) -> typing.Annotated[numpy.typing.NDArray[Real], "[m, n]"]: ...
    def set_print_progress(self, arg0: bool) -> None: ...

class Frame:
    __members__: ClassVar[dict] = ...  # read-only
    ECEF: ClassVar[Frame] = ...
    ECI: ClassVar[Frame] = ...
    EME: ClassVar[Frame] = ...
    EMR: ClassVar[Frame] = ...
    GCRF: ClassVar[Frame] = ...
    GSE: ClassVar[Frame] = ...
    ICRF: ClassVar[Frame] = ...
    ITRF: ClassVar[Frame] = ...
    MARS_FIXED: ClassVar[Frame] = ...
    MOD: ClassVar[Frame] = ...
    MOON_CI: ClassVar[Frame] = ...
    MOON_ME: ClassVar[Frame] = ...
    MOON_OP: ClassVar[Frame] = ...
    MOON_PA: ClassVar[Frame] = ...
    SER: ClassVar[Frame] = ...
    TOD: ClassVar[Frame] = ...
    VENUS_FIXED: ClassVar[Frame] = ...
    __entries: ClassVar[dict] = ...
    def __init__(self, value: typing.SupportsInt | typing.SupportsIndex) -> None: ...
    def __eq__(self, other: object) -> bool: ...
    def __hash__(self) -> int: ...
    def __index__(self) -> int: ...
    def __int__(self) -> int: ...
    def __ne__(self, other: object) -> bool: ...
    @property
    def name(self) -> str: ...
    @property
    def value(self) -> int: ...

class GnssAttitude:
    @overload
    def __init__(self) -> None: ...
    @overload
    def __init__(
        self,
        r_sat_eci: typing.Annotated[numpy.typing.ArrayLike, Real, "[3, 1]"],
        r_sun_eci: typing.Annotated[numpy.typing.ArrayLike, Real, "[3, 1]"],
    ) -> None: ...
    @overload
    @staticmethod
    def compute(
        r_sat_eci: typing.Annotated[numpy.typing.ArrayLike, Real, "[3, 1]"],
        r_sun_eci: typing.Annotated[numpy.typing.ArrayLike, Real, "[3, 1]"],
    ) -> tuple[
        typing.Annotated[numpy.typing.NDArray[Real], "[3, 1]"],
        typing.Annotated[numpy.typing.NDArray[Real], "[3, 1]"],
        typing.Annotated[numpy.typing.NDArray[Real], "[3, 1]"],
    ]: ...
    @overload
    @staticmethod
    def compute(
        r_sat_eci: typing.Annotated[numpy.typing.ArrayLike, Real, "[3, 1]"],
        v_sat_eci: typing.Annotated[numpy.typing.ArrayLike, Real, "[3, 1]"],
        r_sun_eci: typing.Annotated[numpy.typing.ArrayLike, Real, "[3, 1]"],
    ) -> tuple[
        typing.Annotated[numpy.typing.NDArray[Real], "[3, 1]"],
        typing.Annotated[numpy.typing.NDArray[Real], "[3, 1]"],
        typing.Annotated[numpy.typing.NDArray[Real], "[3, 1]"],
    ]: ...
    @overload
    @staticmethod
    def compute(r_sat_eci, r_sun_eci) -> Any: ...
    @staticmethod
    def compute_from_yaw_angle(
        r_sat_eci: typing.Annotated[numpy.typing.ArrayLike, Real, "[3, 1]"],
        v_sat_eci: typing.Annotated[numpy.typing.ArrayLike, Real, "[3, 1]"],
        yaw_angle: Real,
    ) -> tuple[
        typing.Annotated[numpy.typing.NDArray[Real], "[3, 1]"],
        typing.Annotated[numpy.typing.NDArray[Real], "[3, 1]"],
        typing.Annotated[numpy.typing.NDArray[Real], "[3, 1]"],
    ]: ...
    def get_angles(
        self, u: typing.Annotated[numpy.typing.ArrayLike, Real, "[3, 1]"]
    ) -> tuple[Real, Real]: ...
    def get_ex(self) -> typing.Annotated[numpy.typing.NDArray[Real], "[3, 1]"]: ...
    def get_ey(self) -> typing.Annotated[numpy.typing.NDArray[Real], "[3, 1]"]: ...
    def get_ez(self) -> typing.Annotated[numpy.typing.NDArray[Real], "[3, 1]"]: ...
    def get_rotation_matrix(self) -> typing.Annotated[numpy.typing.NDArray[Real], "[3, 3]"]: ...
    @overload
    def update(
        self,
        r_sat_eci: typing.Annotated[numpy.typing.ArrayLike, Real, "[3, 1]"],
        r_sun_eci: typing.Annotated[numpy.typing.ArrayLike, Real, "[3, 1]"],
    ) -> None: ...
    @overload
    def update(
        self,
        r_sat_eci: typing.Annotated[numpy.typing.ArrayLike, Real, "[3, 1]"],
        v_sat_eci: typing.Annotated[numpy.typing.ArrayLike, Real, "[3, 1]"],
        r_sun_eci: typing.Annotated[numpy.typing.ArrayLike, Real, "[3, 1]"],
    ) -> None: ...

class GnssConst:
    __members__: ClassVar[dict] = ...  # read-only
    BEIDOU: ClassVar[GnssConst] = ...
    GALILEO: ClassVar[GnssConst] = ...
    GLONASS: ClassVar[GnssConst] = ...
    GPS: ClassVar[GnssConst] = ...
    QZSS: ClassVar[GnssConst] = ...
    __entries: ClassVar[dict] = ...
    def __init__(self, value: typing.SupportsInt | typing.SupportsIndex) -> None: ...
    def __eq__(self, other: object) -> bool: ...
    def __hash__(self) -> int: ...
    def __index__(self) -> int: ...
    def __int__(self) -> int: ...
    def __ne__(self, other: object) -> bool: ...
    @property
    def name(self) -> str: ...
    @property
    def value(self) -> int: ...

class GnssFreq:
    __members__: ClassVar[dict] = ...  # read-only
    E1: ClassVar[GnssFreq] = ...
    E5: ClassVar[GnssFreq] = ...
    E5a: ClassVar[GnssFreq] = ...
    E5b: ClassVar[GnssFreq] = ...
    E6: ClassVar[GnssFreq] = ...
    L1: ClassVar[GnssFreq] = ...
    L2: ClassVar[GnssFreq] = ...
    L5: ClassVar[GnssFreq] = ...
    __entries: ClassVar[dict] = ...
    def __init__(self, value: typing.SupportsInt | typing.SupportsIndex) -> None: ...
    def __eq__(self, other: object) -> bool: ...
    def __hash__(self) -> int: ...
    def __index__(self) -> int: ...
    def __int__(self) -> int: ...
    def __ne__(self, other: object) -> bool: ...
    @property
    def name(self) -> str: ...
    @property
    def value(self) -> int: ...

class GnssYawSteering:
    def __init__(self, *args, **kwargs) -> None: ...
    @staticmethod
    def bds3_cast_igso_yaw_angle(t: Real, ts: Real, phi_s: Real) -> Real: ...
    @staticmethod
    def bds3_cast_meo_yaw_angle(t: Real, ts: Real, phi_s: Real) -> Real: ...
    @staticmethod
    def bds3_secm_csno_yaw_angle(beta: Real, mu: Real) -> Real: ...
    @staticmethod
    def bds3_secm_mcsno_yaw_angle(
        t: Real,
        t0: Real,
        ts: Real,
        te: Real,
        beta: Real,
        beta_dot: Real,
        mu: Real,
        mu_ts: Real,
        mu_dot: Real,
        phi_ts: Real,
    ) -> Real: ...
    @staticmethod
    def beta_angle(
        r_sat: typing.Annotated[numpy.typing.ArrayLike, Real, "[3, 1]"],
        v_sat: typing.Annotated[numpy.typing.ArrayLike, Real, "[3, 1]"],
        r_sun: typing.Annotated[numpy.typing.ArrayLike, Real, "[3, 1]"],
    ) -> Real: ...
    @staticmethod
    def galileo_foc_yaw_angle(t: Real, ts: Real, phi_s: Real) -> Real: ...
    @staticmethod
    def galileo_iov_eclipse_yaw_angle(eta: Real, beta: Real, phi_nom: Real) -> Real: ...
    @staticmethod
    def galileo_iov_nominal_yaw_angle(eta: Real, beta: Real) -> Real: ...
    @staticmethod
    def galileo_sun_vector(
        eta: Real, beta: Real
    ) -> typing.Annotated[numpy.typing.NDArray[Real], "[3, 1]"]: ...
    @staticmethod
    def gps3_eclipse_yaw_angle(beta: Real, mu: Real, phi_nom: Real) -> Real: ...
    @staticmethod
    def gps3_sun_vector(
        beta: Real, mu: Real
    ) -> typing.Annotated[numpy.typing.NDArray[Real], "[3, 1]"]: ...
    @staticmethod
    def gps_iif_noon_turn_yaw_angle(t: Real, ts: Real, phi_ts: Real, beta: Real) -> Real: ...
    @staticmethod
    def gps_iif_shadow_yaw_angle(
        t: Real, ts: Real, te: Real, phi_ts: Real, phi_te: Real
    ) -> Real: ...
    @staticmethod
    def gps_iir_midnight_turn_yaw_angle(t: Real, ts: Real, phi_ts: Real, beta: Real) -> Real: ...
    @staticmethod
    def gps_iir_noon_turn_yaw_angle(t: Real, ts: Real, phi_ts: Real, beta: Real) -> Real: ...
    @staticmethod
    def nominal_yaw_angle(beta: Real, mu: Real) -> Real: ...
    @staticmethod
    def nominal_yaw_rate(beta: Real, mu: Real, mu_dot: Real) -> Real: ...
    @staticmethod
    def orbit_angle(
        r_sat: typing.Annotated[numpy.typing.ArrayLike, Real, "[3, 1]"],
        v_sat: typing.Annotated[numpy.typing.ArrayLike, Real, "[3, 1]"],
        r_sun: typing.Annotated[numpy.typing.ArrayLike, Real, "[3, 1]"],
    ) -> Real: ...
    @staticmethod
    def orbit_noon_angle(mu: Real) -> Real: ...
    @staticmethod
    def sign(a: Real, b: Real) -> Real: ...

class GravityField:
    def __init__(self) -> None: ...
    @property
    def CS(self) -> typing.Annotated[numpy.typing.NDArray[numpy.float64], "[m, n]"]: ...
    @property
    def GM(self) -> float: ...
    @property
    def R(self) -> float: ...
    @property
    def m(self) -> int: ...
    @property
    def m_max(self) -> int: ...
    @property
    def n(self) -> int: ...
    @property
    def n_max(self) -> int: ...
    @property
    def units(self) -> UnitSystem: ...

class IRI2007Option:
    R12: float
    def __init__(self) -> None: ...
    def update_jf_2007(self) -> None: ...

class IRI2020Option:
    R12: float
    compute_ni: bool
    compute_teti: bool
    output_messages: bool
    output_to_text: bool
    plasma_model: int
    without_plasmapause: int
    def __init__(self) -> None: ...
    def update_jf_2020(self) -> None: ...

class IntegratorParams:
    abstol: float
    max_iter: int
    reltol: float
    @overload
    def __init__(self) -> None: ...
    @overload
    def __init__(
        self,
        max_iter: typing.SupportsInt | typing.SupportsIndex = ...,
        abstol: typing.SupportsFloat | typing.SupportsIndex = ...,
        reltol: typing.SupportsFloat | typing.SupportsIndex = ...,
    ) -> None: ...
    def set_terminate_if(self, callback: collections.abc.Callable) -> None: ...

class IntegratorType:
    __members__: ClassVar[dict] = ...  # read-only
    PD45: ClassVar[IntegratorType] = ...
    RK4: ClassVar[IntegratorType] = ...
    RK8: ClassVar[IntegratorType] = ...
    RKF45: ClassVar[IntegratorType] = ...
    __entries: ClassVar[dict] = ...
    def __init__(self, value: typing.SupportsInt | typing.SupportsIndex) -> None: ...
    def __eq__(self, other: object) -> bool: ...
    def __hash__(self) -> int: ...
    def __index__(self) -> int: ...
    def __int__(self) -> int: ...
    def __ne__(self, other: object) -> bool: ...
    @property
    def name(self) -> str: ...
    @property
    def value(self) -> int: ...

class J2KeplerianDynamics(NumericalOrbitDynamics):
    def __init__(
        self,
        GM: typing.SupportsFloat | typing.SupportsIndex,
        J2: typing.SupportsFloat | typing.SupportsIndex,
        R_body: typing.SupportsFloat | typing.SupportsIndex,
    ) -> None: ...

class JToCartTwoBodyDynamics(NumericalOrbitDynamics):
    def __init__(
        self,
        GM: typing.SupportsFloat | typing.SupportsIndex,
        J2: typing.SupportsFloat | typing.SupportsIndex,
        R_body: typing.SupportsFloat | typing.SupportsIndex,
    ) -> None: ...

class KeplerianDynamics(AnalyticalOrbitDynamics):
    def __init__(self, GM: typing.SupportsFloat | typing.SupportsIndex) -> None: ...

class Logger:
    class LogLevel:
        __members__: ClassVar[dict] = ...  # read-only
        DEBUG: ClassVar[Logger.LogLevel] = ...
        ERROR: ClassVar[Logger.LogLevel] = ...
        INFO: ClassVar[Logger.LogLevel] = ...
        WARNING: ClassVar[Logger.LogLevel] = ...
        __entries: ClassVar[dict] = ...
        def __init__(self, value: typing.SupportsInt | typing.SupportsIndex) -> None: ...
        def __eq__(self, other: object) -> bool: ...
        def __hash__(self) -> int: ...
        def __index__(self) -> int: ...
        def __int__(self) -> int: ...
        def __ne__(self, other: object) -> bool: ...
        @property
        def name(self) -> str: ...
        @property
        def value(self) -> int: ...

    def __init__(self, *args, **kwargs) -> None: ...
    @staticmethod
    def debug(
        message: str, name: str = ..., time_sim: typing.SupportsFloat | typing.SupportsIndex = ...
    ) -> None: ...
    @staticmethod
    def error(
        message: str, name: str = ..., time_sim: typing.SupportsFloat | typing.SupportsIndex = ...
    ) -> None: ...
    @staticmethod
    def get_progress_bar(*args, **kwargs): ...
    @staticmethod
    def info(
        message: str, name: str = ..., time_sim: typing.SupportsFloat | typing.SupportsIndex = ...
    ) -> None: ...
    @staticmethod
    def set_log_level(level) -> None: ...
    @staticmethod
    def warn(
        message: str, name: str = ..., time_sim: typing.SupportsFloat | typing.SupportsIndex = ...
    ) -> None: ...

class NBodyDynamics(NumericalOrbitDynamics):
    def __init__(self) -> None: ...
    def add_body(self, body) -> None: ...
    def get_bodies(self, *args, **kwargs): ...
    def get_drag_coeff(self) -> float: ...
    def get_srp_coeff(self) -> float: ...
    def get_units(self) -> UnitSystem: ...
    def get_use_relativity(self) -> bool: ...
    def set_autodiff(self, arg0: bool) -> None: ...
    def set_drag_coeff(self, bcoeff: Real) -> None: ...
    def set_frame(self, frame: Frame) -> None: ...
    def set_srp_coeff(self, CR: Real, area: Real, mass: Real) -> None: ...
    def set_units(self, units: UnitSystem) -> None: ...
    def set_use_relativity(self, use_relativity: bool) -> None: ...

class NumericalOrbitDynamics(Dynamics):
    def __init__(self, *args, **kwargs) -> None: ...
    def compute_rates(
        self,
        arg0: typing.SupportsFloat | typing.SupportsIndex,
        arg1: typing.Annotated[numpy.typing.ArrayLike, numpy.float64, "[m, 1]"],
    ) -> typing.Annotated[numpy.typing.NDArray[numpy.float64], "[m, 1]"]: ...
    def get_time_step(self) -> float: ...
    def propagate_stm_with_info(
        self, arg0: typing.Annotated[numpy.typing.ArrayLike, Real, "[m, 1]"], arg1: Real, arg2: Real
    ) -> object: ...
    @overload
    def propagate_with_info(
        self, arg0: typing.Annotated[numpy.typing.ArrayLike, Real, "[m, 1]"], arg1: Real, arg2: Real
    ) -> object: ...
    @overload
    def propagate_with_info(
        self,
        arg0: typing.Annotated[numpy.typing.ArrayLike, Real, "[m, 1]"],
        arg1: Real,
        arg2: typing.Annotated[numpy.typing.ArrayLike, Real, "[m, 1]"],
    ) -> object: ...
    def set_integrator(self, arg0: IntegratorType) -> None: ...
    def set_integrator_params(self, arg0: IntegratorParams) -> None: ...
    def set_ode_function(self, *args, **kwargs): ...
    def set_time_step(self, arg0: typing.SupportsFloat | typing.SupportsIndex) -> None: ...

class PathProfile:
    az_dir: typing.Annotated[numpy.typing.NDArray[numpy.float64], "[m, 1]"]
    corr_final_pos_err: typing.Annotated[numpy.typing.NDArray[numpy.float64], "[3, 1]"]
    corr_final_time_err: float
    dir_end: typing.Annotated[numpy.typing.NDArray[numpy.float64], "[3, 1]"]
    dir_start: typing.Annotated[numpy.typing.NDArray[numpy.float64], "[3, 1]"]
    dist_bend_m: float
    dist_straight_km: float
    dist_to_line: typing.Annotated[numpy.typing.NDArray[numpy.float64], "[m, 1]"]
    el_dir: typing.Annotated[numpy.typing.NDArray[numpy.float64], "[m, 1]"]
    final_pos: typing.Annotated[numpy.typing.NDArray[numpy.float64], "[3, 1]"]
    max_sep_line_m: float
    pos_eci: typing.Annotated[numpy.typing.NDArray[numpy.float64], "[m, n]"]
    prop_time_total: float
    r: typing.Annotated[numpy.typing.NDArray[numpy.float64], "[m, 1]"]
    s: typing.Annotated[numpy.typing.NDArray[numpy.float64], "[m, 1]"]
    second_delay_m: float
    sf: float
    t_rx: float
    t_tx: float
    tec_delay_bend_m: float
    tec_delay_m: float
    tec_section: typing.Annotated[numpy.typing.NDArray[numpy.float64], "[m, 1]"]
    tecu: float
    tecu_bend: float
    third_delay_m: float
    total_delay_m: float
    def __init__(self) -> None: ...

class PhysicalConstants:
    def __init__(self, *args, **kwargs) -> None: ...
    @property
    def AU(self) -> float: ...
    @property
    def C(self) -> float: ...
    @property
    def GM_EARTH(self) -> float: ...
    @property
    def GM_MARS(self) -> float: ...
    @property
    def GM_MOON(self) -> float: ...
    @property
    def GM_SUN(self) -> float: ...
    @property
    def OMEGA_EARTH(self) -> float: ...
    @property
    def OMEGA_MOON(self) -> float: ...
    @property
    def P_SUN(self) -> float: ...
    @property
    def R_EARTH(self) -> float: ...
    @property
    def R_MARS(self) -> float: ...
    @property
    def R_MOON(self) -> float: ...
    @property
    def R_SUN(self) -> float: ...
    @property
    def WGS84_A(self) -> float: ...
    @property
    def coordinate_scale(self): ...

class ProgressBar:
    def __init__(self, *args, **kwargs) -> None: ...
    def finish(self) -> None: ...
    def is_done(self) -> bool: ...
    def reset(self) -> None: ...
    def set_description(self, description: str) -> None: ...
    def set_leave(self, leave: bool) -> None: ...
    def set_max_update_freq(
        self, max_update_freq: typing.SupportsFloat | typing.SupportsIndex
    ) -> None: ...
    def set_width(self, width: typing.SupportsInt | typing.SupportsIndex) -> None: ...
    @overload
    def update(self) -> None: ...
    @overload
    def update(self, value: typing.SupportsInt | typing.SupportsIndex) -> None: ...

class RayTraceConfig:
    compute_higher_order: bool
    corr_tol: float
    correction: bool
    correction_method: str
    cutoff_r: float
    fine_correction: bool
    freq_Hz: float
    gradn_dx: float
    integ_method: str
    kp: float
    step_size: float
    straight_ray: bool
    use_adaptive_step: bool
    use_fortran_gcpm: bool
    def __init__(self) -> None: ...

class RinexNavLoader:
    @overload
    def __init__(self) -> None: ...
    @overload
    def __init__(self, filepath: str) -> None: ...
    @overload
    def __init__(self, filepaths: collections.abc.Sequence[str]) -> None: ...
    def get_pos_vel(
        self, sat_id: str, t_tai: Real
    ) -> typing.Annotated[numpy.typing.NDArray[Real], "[6, 1]"]: ...
    def get_pos_vel_clock(
        self, sat_id: str, t_tai: Real
    ) -> tuple[typing.Annotated[numpy.typing.NDArray[Real], "[6, 1]"], Real]: ...
    def get_satellites(self) -> list[str]: ...
    def has_satellite(self, sat_id: str) -> bool: ...
    def load_file(self, filepath: str) -> None: ...

class Satellite:
    GM_: float
    coe_: typing.Annotated[numpy.typing.NDArray[numpy.float64], "[6, 1]"]
    epoch_utc_: float
    id_: int
    posvel_: typing.Annotated[numpy.typing.NDArray[numpy.float64], "[6, 1]"]
    def __init__(
        self,
        id: typing.SupportsInt | typing.SupportsIndex,
        coe: typing.Annotated[numpy.typing.ArrayLike, numpy.float64, "[6, 1]"],
        epoch_utc: typing.SupportsFloat | typing.SupportsIndex,
        GM: typing.SupportsFloat | typing.SupportsIndex = ...,
    ) -> None: ...
    def get_pos(self) -> typing.Annotated[numpy.typing.NDArray[numpy.float64], "[3, 1]"]: ...
    def get_pos_epoch(
        self, dt: typing.SupportsFloat | typing.SupportsIndex
    ) -> typing.Annotated[numpy.typing.NDArray[numpy.float64], "[3, 1]"]: ...
    def propagate(self, epoch_utc_new: typing.SupportsFloat | typing.SupportsIndex) -> None: ...

class Sp3Loader:
    @overload
    def __init__(self) -> None: ...
    @overload
    def __init__(self, filepath: str) -> None: ...
    @overload
    def __init__(self, filepaths: collections.abc.Sequence[str]) -> None: ...
    def get_pos_vel(
        self, sat_id: str, t_tai: Real
    ) -> typing.Annotated[numpy.typing.NDArray[Real], "[6, 1]"]: ...
    def get_pos_vel_clock(
        self, sat_id: str, t_tai: Real
    ) -> tuple[typing.Annotated[numpy.typing.NDArray[Real], "[6, 1]"], Real]: ...
    def get_satellites(self) -> list[str]: ...
    def get_time_span(self, sat_id: str) -> tuple[float, float]: ...
    def has_satellite(self, sat_id: str) -> bool: ...
    def load_file(self, filepath: str) -> None: ...

class TLE:
    def __init__(self, *args, **kwargs) -> None: ...
    @staticmethod
    def from_file(filename: str) -> list[TLE]: ...
    @staticmethod
    def from_lines(line1: str, line2: str, line3: str) -> TLE: ...
    @property
    def arg_perigee(self) -> float: ...
    @property
    def bstar(self) -> float: ...
    @property
    def eccentricity(self) -> float: ...
    @property
    def epoch_day(self) -> float: ...
    @property
    def epoch_tai(self) -> float: ...
    @property
    def epoch_year(self) -> float: ...
    @property
    def inclination(self) -> float: ...
    @property
    def mean_anomaly(self) -> float: ...
    @property
    def mean_motion(self) -> float: ...
    @property
    def name(self) -> str: ...
    @property
    def prn(self) -> int: ...
    @property
    def raan(self) -> float: ...

class TerminationInfo:
    def __init__(self, *args, **kwargs) -> None: ...
    @property
    def reason(self) -> TerminationReason: ...
    @property
    def steps(self) -> int: ...
    @property
    def t_stop(self) -> Real: ...
    @property
    def terminated(self) -> bool: ...

class TerminationReason:
    __members__: ClassVar[dict] = ...  # read-only
    ReachedTf: ClassVar[TerminationReason] = ...
    UserCondition: ClassVar[TerminationReason] = ...
    __entries: ClassVar[dict] = ...
    def __init__(self, value: typing.SupportsInt | typing.SupportsIndex) -> None: ...
    def __eq__(self, other: object) -> bool: ...
    def __hash__(self) -> int: ...
    def __index__(self) -> int: ...
    def __int__(self) -> int: ...
    def __ne__(self, other: object) -> bool: ...
    @property
    def name(self) -> str: ...
    @property
    def value(self) -> int: ...

class Time:
    __members__: ClassVar[dict] = ...  # read-only
    GPS: ClassVar[Time] = ...
    JD_TDB: ClassVar[Time] = ...
    JD_TT: ClassVar[Time] = ...
    LT: ClassVar[Time] = ...
    TAI: ClassVar[Time] = ...
    TCB: ClassVar[Time] = ...
    TCG: ClassVar[Time] = ...
    TCL: ClassVar[Time] = ...
    TDB: ClassVar[Time] = ...
    TT: ClassVar[Time] = ...
    UT1: ClassVar[Time] = ...
    UTC: ClassVar[Time] = ...
    __entries: ClassVar[dict] = ...
    def __init__(self, value: typing.SupportsInt | typing.SupportsIndex) -> None: ...
    def __eq__(self, other: object) -> bool: ...
    def __hash__(self) -> int: ...
    def __index__(self) -> int: ...
    def __int__(self) -> int: ...
    def __ne__(self, other: object) -> bool: ...
    @property
    def name(self) -> str: ...
    @property
    def value(self) -> int: ...

class UnitSystem:
    length: float
    mass: float
    time: float
    def __init__(
        self,
        length: typing.SupportsFloat | typing.SupportsIndex = ...,
        time: typing.SupportsFloat | typing.SupportsIndex = ...,
        mass: typing.SupportsFloat | typing.SupportsIndex = ...,
    ) -> None: ...
    def acceleration_from_si(self, arg0: typing.SupportsFloat | typing.SupportsIndex) -> float: ...
    def area_from_si(self, arg0: typing.SupportsFloat | typing.SupportsIndex) -> float: ...
    def area_per_mass_from_si(self, arg0: typing.SupportsFloat | typing.SupportsIndex) -> float: ...
    def from_si(
        self,
        value: typing.SupportsFloat | typing.SupportsIndex,
        length_power: typing.SupportsInt | typing.SupportsIndex,
        time_power: typing.SupportsInt | typing.SupportsIndex = ...,
        mass_power: typing.SupportsInt | typing.SupportsIndex = ...,
    ) -> float: ...
    def gm_from_si(self, arg0: typing.SupportsFloat | typing.SupportsIndex) -> float: ...
    def length_from_si(self, arg0: typing.SupportsFloat | typing.SupportsIndex) -> float: ...
    def pressure_from_si(self, arg0: typing.SupportsFloat | typing.SupportsIndex) -> float: ...
    def to_si(
        self,
        value: typing.SupportsFloat | typing.SupportsIndex,
        length_power: typing.SupportsInt | typing.SupportsIndex,
        time_power: typing.SupportsInt | typing.SupportsIndex = ...,
        mass_power: typing.SupportsInt | typing.SupportsIndex = ...,
    ) -> float: ...
    def velocity_from_si(self, arg0: typing.SupportsFloat | typing.SupportsIndex) -> float: ...

class ostream_redirect_plasma:
    def __init__(self, stdout: bool = ..., stderr: bool = ...) -> None: ...
    def __enter__(self) -> None: ...
    def __exit__(self, *args) -> None: ...

def add_config_search_dir(dir: str) -> None: ...
def are_coordinate_scales_convertible(_from: CoordinateScale, to: CoordinateScale) -> bool: ...
@overload
def az_el_range_to_cart(
    aer: typing.Annotated[numpy.typing.ArrayLike, Real, "[3, 1]"],
    xyz_ref: typing.Annotated[numpy.typing.ArrayLike, Real, "[3, 1]"],
) -> typing.Annotated[numpy.typing.NDArray[Real], "[3, 1]"]: ...
@overload
def az_el_range_to_cart(
    aer: typing.Annotated[numpy.typing.ArrayLike, Real, "[m, 3]"],
    xyz_ref: typing.Annotated[numpy.typing.ArrayLike, Real, "[3, 1]"],
) -> typing.Annotated[numpy.typing.NDArray[Real], "[m, 3]"]: ...
@overload
def az_el_range_to_cart(
    aer: typing.Annotated[numpy.typing.ArrayLike, Real, "[3, 1]"],
    xyz_ref: typing.Annotated[numpy.typing.ArrayLike, Real, "[m, 3]"],
) -> typing.Annotated[numpy.typing.NDArray[Real], "[m, 3]"]: ...
@overload
def az_el_range_to_cart(
    aer: typing.Annotated[numpy.typing.ArrayLike, Real, "[m, 3]"],
    xyz_ref: typing.Annotated[numpy.typing.ArrayLike, Real, "[m, 3]"],
) -> typing.Annotated[numpy.typing.NDArray[Real], "[m, 3]"]: ...
@overload
def az_el_range_to_east_north_up(
    aer: typing.Annotated[numpy.typing.ArrayLike, Real, "[3, 1]"],
) -> typing.Annotated[numpy.typing.NDArray[Real], "[3, 1]"]: ...
@overload
def az_el_range_to_east_north_up(
    aer: typing.Annotated[numpy.typing.ArrayLike, Real, "[m, 3]"],
) -> typing.Annotated[numpy.typing.NDArray[Real], "[m, 3]"]: ...
def cart2coe(
    posvel: typing.Annotated[numpy.typing.ArrayLike, numpy.float64, "[6, 1]"],
    GM: typing.SupportsFloat | typing.SupportsIndex,
) -> typing.Annotated[numpy.typing.NDArray[numpy.float64], "[6, 1]"]: ...
@overload
def cart_to_az_el_range(
    xyz: typing.Annotated[numpy.typing.ArrayLike, Real, "[3, 1]"],
    xyz_ref: typing.Annotated[numpy.typing.ArrayLike, Real, "[3, 1]"],
) -> typing.Annotated[numpy.typing.NDArray[Real], "[3, 1]"]: ...
@overload
def cart_to_az_el_range(
    xyz: typing.Annotated[numpy.typing.ArrayLike, Real, "[m, 3]"],
    xyz_ref: typing.Annotated[numpy.typing.ArrayLike, Real, "[3, 1]"],
) -> typing.Annotated[numpy.typing.NDArray[Real], "[m, 3]"]: ...
@overload
def cart_to_az_el_range(
    xyz: typing.Annotated[numpy.typing.ArrayLike, Real, "[3, 1]"],
    xyz_ref: typing.Annotated[numpy.typing.ArrayLike, Real, "[m, 3]"],
) -> typing.Annotated[numpy.typing.NDArray[Real], "[m, 3]"]: ...
@overload
def cart_to_az_el_range(
    xyz: typing.Annotated[numpy.typing.ArrayLike, Real, "[m, 3]"],
    xyz_ref: typing.Annotated[numpy.typing.ArrayLike, Real, "[m, 3]"],
) -> typing.Annotated[numpy.typing.NDArray[Real], "[m, 3]"]: ...
@overload
def cart_to_classical(
    cart: typing.Annotated[numpy.typing.ArrayLike, Real, "[6, 1]"], GM: Real
) -> typing.Annotated[numpy.typing.NDArray[Real], "[6, 1]"]: ...
@overload
def cart_to_classical(
    cart: typing.Annotated[numpy.typing.ArrayLike, Real, "[6, 1]"],
    GM: typing.Annotated[numpy.typing.ArrayLike, Real, "[m, 1]"],
) -> typing.Annotated[numpy.typing.NDArray[Real], "[m, 6]"]: ...
@overload
def cart_to_classical(
    cart: typing.Annotated[numpy.typing.ArrayLike, Real, "[m, 6]"], GM: Real
) -> typing.Annotated[numpy.typing.NDArray[Real], "[m, 6]"]: ...
@overload
def cart_to_classical(
    cart: typing.Annotated[numpy.typing.ArrayLike, Real, "[m, 6]"],
    GM: typing.Annotated[numpy.typing.ArrayLike, Real, "[m, 1]"],
) -> typing.Annotated[numpy.typing.NDArray[Real], "[m, 6]"]: ...
@overload
def cart_to_east_north_up(
    xyz: typing.Annotated[numpy.typing.ArrayLike, Real, "[3, 1]"],
    xyz_ref: typing.Annotated[numpy.typing.ArrayLike, Real, "[3, 1]"],
) -> typing.Annotated[numpy.typing.NDArray[Real], "[3, 1]"]: ...
@overload
def cart_to_east_north_up(
    xyz: typing.Annotated[numpy.typing.ArrayLike, Real, "[m, 3]"],
    xyz_ref: typing.Annotated[numpy.typing.ArrayLike, Real, "[3, 1]"],
) -> typing.Annotated[numpy.typing.NDArray[Real], "[m, 3]"]: ...
@overload
def cart_to_east_north_up(
    xyz: typing.Annotated[numpy.typing.ArrayLike, Real, "[3, 1]"],
    xyz_ref: typing.Annotated[numpy.typing.ArrayLike, Real, "[m, 3]"],
) -> typing.Annotated[numpy.typing.NDArray[Real], "[m, 3]"]: ...
@overload
def cart_to_east_north_up(
    xyz: typing.Annotated[numpy.typing.ArrayLike, Real, "[m, 3]"],
    xyz_ref: typing.Annotated[numpy.typing.ArrayLike, Real, "[m, 3]"],
) -> typing.Annotated[numpy.typing.NDArray[Real], "[m, 3]"]: ...
@overload
def cart_to_lat_lon_alt(
    xyz: typing.Annotated[numpy.typing.ArrayLike, Real, "[3, 1]"], R_body: Real
) -> typing.Annotated[numpy.typing.NDArray[Real], "[3, 1]"]: ...
@overload
def cart_to_lat_lon_alt(
    xyz: typing.Annotated[numpy.typing.ArrayLike, Real, "[3, 1]"],
    R_body: typing.Annotated[numpy.typing.ArrayLike, Real, "[m, 1]"],
) -> typing.Annotated[numpy.typing.NDArray[Real], "[m, 3]"]: ...
@overload
def cart_to_lat_lon_alt(
    xyz: typing.Annotated[numpy.typing.ArrayLike, Real, "[m, 3]"], R_body: Real
) -> typing.Annotated[numpy.typing.NDArray[Real], "[m, 3]"]: ...
@overload
def cart_to_lat_lon_alt(
    xyz: typing.Annotated[numpy.typing.ArrayLike, Real, "[m, 3]"],
    R_body: typing.Annotated[numpy.typing.ArrayLike, Real, "[m, 1]"],
) -> typing.Annotated[numpy.typing.NDArray[Real], "[m, 3]"]: ...
@overload
def cart_to_stereographic(
    xyz: typing.Annotated[numpy.typing.ArrayLike, Real, "[3, 1]"], R_body: Real
) -> typing.Annotated[numpy.typing.NDArray[Real], "[3, 1]"]: ...
@overload
def cart_to_stereographic(
    xyz: typing.Annotated[numpy.typing.ArrayLike, Real, "[3, 1]"],
    R_body: typing.Annotated[numpy.typing.ArrayLike, Real, "[m, 1]"],
) -> typing.Annotated[numpy.typing.NDArray[Real], "[m, 3]"]: ...
@overload
def cart_to_stereographic(
    xyz: typing.Annotated[numpy.typing.ArrayLike, Real, "[m, 3]"], R_body: Real
) -> typing.Annotated[numpy.typing.NDArray[Real], "[m, 3]"]: ...
@overload
def cart_to_stereographic(
    xyz: typing.Annotated[numpy.typing.ArrayLike, Real, "[m, 3]"],
    R_body: typing.Annotated[numpy.typing.ArrayLike, Real, "[m, 1]"],
) -> typing.Annotated[numpy.typing.NDArray[Real], "[m, 3]"]: ...
@overload
def classical_to_cart(
    coe: typing.Annotated[numpy.typing.ArrayLike, Real, "[6, 1]"], GM: Real
) -> typing.Annotated[numpy.typing.NDArray[Real], "[6, 1]"]: ...
@overload
def classical_to_cart(
    coe: typing.Annotated[numpy.typing.ArrayLike, Real, "[6, 1]"],
    GM: typing.Annotated[numpy.typing.ArrayLike, Real, "[m, 1]"],
) -> typing.Annotated[numpy.typing.NDArray[Real], "[m, 6]"]: ...
@overload
def classical_to_cart(
    coe: typing.Annotated[numpy.typing.ArrayLike, Real, "[m, 6]"], GM: Real
) -> typing.Annotated[numpy.typing.NDArray[Real], "[m, 6]"]: ...
@overload
def classical_to_cart(
    coe: typing.Annotated[numpy.typing.ArrayLike, Real, "[m, 6]"],
    GM: typing.Annotated[numpy.typing.ArrayLike, Real, "[m, 1]"],
) -> typing.Annotated[numpy.typing.NDArray[Real], "[m, 6]"]: ...
@overload
def classical_to_delaunay(
    coe: typing.Annotated[numpy.typing.ArrayLike, Real, "[6, 1]"], GM: Real
) -> typing.Annotated[numpy.typing.NDArray[Real], "[6, 1]"]: ...
@overload
def classical_to_delaunay(
    coe: typing.Annotated[numpy.typing.ArrayLike, Real, "[6, 1]"],
    GM: typing.Annotated[numpy.typing.ArrayLike, Real, "[m, 1]"],
) -> typing.Annotated[numpy.typing.NDArray[Real], "[m, 6]"]: ...
@overload
def classical_to_delaunay(
    coe: typing.Annotated[numpy.typing.ArrayLike, Real, "[m, 6]"], GM: Real
) -> typing.Annotated[numpy.typing.NDArray[Real], "[m, 6]"]: ...
@overload
def classical_to_delaunay(
    coe: typing.Annotated[numpy.typing.ArrayLike, Real, "[m, 6]"],
    GM: typing.Annotated[numpy.typing.ArrayLike, Real, "[m, 1]"],
) -> typing.Annotated[numpy.typing.NDArray[Real], "[m, 6]"]: ...
@overload
def classical_to_delaunay(
    coe: typing.Annotated[numpy.typing.ArrayLike, Real, "[6, 1]"], GM: Real
) -> typing.Annotated[numpy.typing.NDArray[Real], "[6, 1]"]: ...
@overload
def classical_to_delaunay(
    coe: typing.Annotated[numpy.typing.ArrayLike, Real, "[6, 1]"],
    GM: typing.Annotated[numpy.typing.ArrayLike, Real, "[m, 1]"],
) -> typing.Annotated[numpy.typing.NDArray[Real], "[m, 6]"]: ...
@overload
def classical_to_delaunay(
    coe: typing.Annotated[numpy.typing.ArrayLike, Real, "[m, 6]"], GM: Real
) -> typing.Annotated[numpy.typing.NDArray[Real], "[m, 6]"]: ...
@overload
def classical_to_delaunay(
    coe: typing.Annotated[numpy.typing.ArrayLike, Real, "[m, 6]"],
    GM: typing.Annotated[numpy.typing.ArrayLike, Real, "[m, 1]"],
) -> typing.Annotated[numpy.typing.NDArray[Real], "[m, 6]"]: ...
@overload
def classical_to_delaunay(
    coe: typing.Annotated[numpy.typing.ArrayLike, Real, "[6, 1]"], GM: Real
) -> typing.Annotated[numpy.typing.NDArray[Real], "[6, 1]"]: ...
@overload
def classical_to_delaunay(
    coe: typing.Annotated[numpy.typing.ArrayLike, Real, "[6, 1]"],
    GM: typing.Annotated[numpy.typing.ArrayLike, Real, "[m, 1]"],
) -> typing.Annotated[numpy.typing.NDArray[Real], "[m, 6]"]: ...
@overload
def classical_to_delaunay(
    coe: typing.Annotated[numpy.typing.ArrayLike, Real, "[m, 6]"], GM: Real
) -> typing.Annotated[numpy.typing.NDArray[Real], "[m, 6]"]: ...
@overload
def classical_to_delaunay(
    coe: typing.Annotated[numpy.typing.ArrayLike, Real, "[m, 6]"],
    GM: typing.Annotated[numpy.typing.ArrayLike, Real, "[m, 1]"],
) -> typing.Annotated[numpy.typing.NDArray[Real], "[m, 6]"]: ...
@overload
def classical_to_delaunay(
    coe: typing.Annotated[numpy.typing.ArrayLike, Real, "[6, 1]"], GM: Real
) -> typing.Annotated[numpy.typing.NDArray[Real], "[6, 1]"]: ...
@overload
def classical_to_delaunay(
    coe: typing.Annotated[numpy.typing.ArrayLike, Real, "[6, 1]"],
    GM: typing.Annotated[numpy.typing.ArrayLike, Real, "[m, 1]"],
) -> typing.Annotated[numpy.typing.NDArray[Real], "[m, 6]"]: ...
@overload
def classical_to_delaunay(
    coe: typing.Annotated[numpy.typing.ArrayLike, Real, "[m, 6]"], GM: Real
) -> typing.Annotated[numpy.typing.NDArray[Real], "[m, 6]"]: ...
@overload
def classical_to_delaunay(
    coe: typing.Annotated[numpy.typing.ArrayLike, Real, "[m, 6]"],
    GM: typing.Annotated[numpy.typing.ArrayLike, Real, "[m, 1]"],
) -> typing.Annotated[numpy.typing.NDArray[Real], "[m, 6]"]: ...
@overload
def classical_to_delaunay(
    coe: typing.Annotated[numpy.typing.ArrayLike, Real, "[6, 1]"], GM: Real
) -> typing.Annotated[numpy.typing.NDArray[Real], "[6, 1]"]: ...
@overload
def classical_to_delaunay(
    coe: typing.Annotated[numpy.typing.ArrayLike, Real, "[6, 1]"],
    GM: typing.Annotated[numpy.typing.ArrayLike, Real, "[m, 1]"],
) -> typing.Annotated[numpy.typing.NDArray[Real], "[m, 6]"]: ...
@overload
def classical_to_delaunay(
    coe: typing.Annotated[numpy.typing.ArrayLike, Real, "[m, 6]"], GM: Real
) -> typing.Annotated[numpy.typing.NDArray[Real], "[m, 6]"]: ...
@overload
def classical_to_delaunay(
    coe: typing.Annotated[numpy.typing.ArrayLike, Real, "[m, 6]"],
    GM: typing.Annotated[numpy.typing.ArrayLike, Real, "[m, 1]"],
) -> typing.Annotated[numpy.typing.NDArray[Real], "[m, 6]"]: ...
@overload
def classical_to_equinoctial(
    coe: typing.Annotated[numpy.typing.ArrayLike, Real, "[6, 1]"], GM: Real
) -> typing.Annotated[numpy.typing.NDArray[Real], "[6, 1]"]: ...
@overload
def classical_to_equinoctial(
    coe: typing.Annotated[numpy.typing.ArrayLike, Real, "[6, 1]"],
    GM: typing.Annotated[numpy.typing.ArrayLike, Real, "[m, 1]"],
) -> typing.Annotated[numpy.typing.NDArray[Real], "[m, 6]"]: ...
@overload
def classical_to_equinoctial(
    coe: typing.Annotated[numpy.typing.ArrayLike, Real, "[m, 6]"], GM: Real
) -> typing.Annotated[numpy.typing.NDArray[Real], "[m, 6]"]: ...
@overload
def classical_to_equinoctial(
    coe: typing.Annotated[numpy.typing.ArrayLike, Real, "[m, 6]"],
    GM: typing.Annotated[numpy.typing.ArrayLike, Real, "[m, 1]"],
) -> typing.Annotated[numpy.typing.NDArray[Real], "[m, 6]"]: ...
@overload
def classical_to_quasi_nonsingular(
    coe: typing.Annotated[numpy.typing.ArrayLike, Real, "[6, 1]"], GM: Real
) -> typing.Annotated[numpy.typing.NDArray[Real], "[6, 1]"]: ...
@overload
def classical_to_quasi_nonsingular(
    coe: typing.Annotated[numpy.typing.ArrayLike, Real, "[6, 1]"],
    GM: typing.Annotated[numpy.typing.ArrayLike, Real, "[m, 1]"],
) -> typing.Annotated[numpy.typing.NDArray[Real], "[m, 6]"]: ...
@overload
def classical_to_quasi_nonsingular(
    coe: typing.Annotated[numpy.typing.ArrayLike, Real, "[m, 6]"], GM: Real
) -> typing.Annotated[numpy.typing.NDArray[Real], "[m, 6]"]: ...
@overload
def classical_to_quasi_nonsingular(
    coe: typing.Annotated[numpy.typing.ArrayLike, Real, "[m, 6]"],
    GM: typing.Annotated[numpy.typing.ArrayLike, Real, "[m, 1]"],
) -> typing.Annotated[numpy.typing.NDArray[Real], "[m, 6]"]: ...
def coe2cart(
    coe: typing.Annotated[numpy.typing.ArrayLike, numpy.float64, "[6, 1]"],
    GM: typing.SupportsFloat | typing.SupportsIndex,
) -> typing.Annotated[numpy.typing.NDArray[numpy.float64], "[6, 1]"]: ...
def compute_B(
    t_j2000: typing.SupportsFloat | typing.SupportsIndex,
    pos_geo: typing.Annotated[numpy.typing.ArrayLike, numpy.float64, "[3, 1]"],
    config: RayTraceConfig,
    debug: bool = ...,
) -> typing.Annotated[numpy.typing.NDArray[numpy.float64], "[3, 1]"]: ...
def compute_eop_from_spice(
    t_tdb: typing.SupportsFloat | typing.SupportsIndex,
) -> typing.Annotated[numpy.typing.NDArray[numpy.float64], "[3, 1]"]: ...
def compute_min_altitude(
    pos1: typing.Annotated[numpy.typing.ArrayLike, numpy.float64, "[3, 1]"],
    pos2: typing.Annotated[numpy.typing.ArrayLike, numpy.float64, "[3, 1]"],
    radius: typing.SupportsFloat | typing.SupportsIndex,
) -> float: ...
def compute_ne(
    t_j2000: typing.SupportsFloat | typing.SupportsIndex,
    pos_geo: typing.Annotated[numpy.typing.ArrayLike, numpy.float64, "[3, 1]"],
    config: RayTraceConfig,
    debug: bool = ...,
) -> float: ...
def compute_vis(
    pos1: typing.Annotated[numpy.typing.ArrayLike, numpy.float64, "[3, 1]"],
    pos2: typing.Annotated[numpy.typing.ArrayLike, numpy.float64, "[3, 1]"],
    radius: typing.SupportsFloat | typing.SupportsIndex,
    max_angle: typing.SupportsFloat | typing.SupportsIndex,
) -> bool: ...
def config_to_string(config: Config) -> str: ...
@overload
def convert_coordinate_time(t: Real, from_time: Time, to_time: Time) -> Real: ...
@overload
def convert_coordinate_time(
    t: Real,
    from_time: Time,
    to_time: Time,
    x_bcrs: typing.Annotated[numpy.typing.ArrayLike, Real, "[3, 1]"],
) -> Real: ...
@overload
def convert_coordinate_time(
    t: typing.Annotated[numpy.typing.ArrayLike, Real, "[m, 1]"], from_time: Time, to_time: Time
) -> typing.Annotated[numpy.typing.NDArray[Real], "[m, 1]"]: ...
@overload
def convert_coordinate_time(
    t: typing.Annotated[numpy.typing.ArrayLike, Real, "[m, 1]"],
    from_time: Time,
    to_time: Time,
    x_bcrs: typing.Annotated[numpy.typing.ArrayLike, Real, "[m, 3]"],
) -> typing.Annotated[numpy.typing.NDArray[Real], "[m, 1]"]: ...
@overload
def convert_frame(
    t_tdb: Real,
    rv_in: typing.Annotated[numpy.typing.ArrayLike, Real, "[6, 1]"],
    frame_in: Frame,
    frame_out: Frame,
    rotate_only: bool = ...,
) -> typing.Annotated[numpy.typing.NDArray[Real], "[6, 1]"]: ...
@overload
def convert_frame(
    t_tdb: Real,
    r_in: typing.Annotated[numpy.typing.ArrayLike, Real, "[3, 1]"],
    frame_in: Frame,
    frame_out: Frame,
    rotate_only: bool = ...,
) -> typing.Annotated[numpy.typing.NDArray[Real], "[3, 1]"]: ...
@overload
def convert_frame(
    t_tdb: typing.Annotated[numpy.typing.ArrayLike, Real, "[m, 1]"],
    rv_in: typing.Annotated[numpy.typing.ArrayLike, Real, "[6, 1]"],
    frame_in: Frame,
    frame_out: Frame,
    rotate_only: bool = ...,
) -> typing.Annotated[numpy.typing.NDArray[Real], "[m, 6]"]: ...
@overload
def convert_frame(
    t_tdb: typing.Annotated[numpy.typing.ArrayLike, Real, "[m, 1]"],
    r_in: typing.Annotated[numpy.typing.ArrayLike, Real, "[3, 1]"],
    frame_in: Frame,
    frame_out: Frame,
    rotate_only: bool = ...,
) -> typing.Annotated[numpy.typing.NDArray[Real], "[m, 3]"]: ...
@overload
def convert_frame(
    t_tdb: Real,
    rv_in: typing.Annotated[numpy.typing.ArrayLike, Real, "[m, 6]"],
    frame_in: Frame,
    frame_out: Frame,
    rotate_only: bool = ...,
) -> typing.Annotated[numpy.typing.NDArray[Real], "[m, 6]"]: ...
@overload
def convert_frame(
    t_tdb: Real,
    r_in: typing.Annotated[numpy.typing.ArrayLike, Real, "[m, 3]"],
    frame_in: Frame,
    frame_out: Frame,
    rotate_only: bool = ...,
) -> typing.Annotated[numpy.typing.NDArray[Real], "[m, 3]"]: ...
@overload
def convert_frame(
    t_tdb: typing.Annotated[numpy.typing.ArrayLike, Real, "[m, 1]"],
    rv_in: typing.Annotated[numpy.typing.ArrayLike, Real, "[m, 6]"],
    frame_in: Frame,
    frame_out: Frame,
    rotate_only: bool = ...,
) -> typing.Annotated[numpy.typing.NDArray[Real], "[m, 6]"]: ...
@overload
def convert_frame(
    t_tdb: typing.Annotated[numpy.typing.ArrayLike, Real, "[m, 1]"],
    r_in: typing.Annotated[numpy.typing.ArrayLike, Real, "[m, 3]"],
    frame_in: Frame,
    frame_out: Frame,
    rotate_only: bool = ...,
) -> typing.Annotated[numpy.typing.NDArray[Real], "[m, 3]"]: ...
@overload
def convert_time(t_tai: Real, from_time: Time, to_time: Time) -> Real: ...
@overload
def convert_time(
    t_tai: typing.Annotated[numpy.typing.ArrayLike, Real, "[m, 1]"], from_time: Time, to_time: Time
) -> typing.Annotated[numpy.typing.NDArray[Real], "[m, 1]"]: ...
def coordinate_scale_factor(scale: CoordinateScale) -> float: ...
def coordinate_scale_ratio(_from: CoordinateScale, to: CoordinateScale) -> float: ...
@overload
def create_body(
    id: BodyId,
    n: typing.SupportsInt | typing.SupportsIndex = ...,
    m: typing.SupportsInt | typing.SupportsIndex = ...,
) -> Body: ...
@overload
def create_body(
    id: BodyId,
    units: UnitSystem,
    n: typing.SupportsInt | typing.SupportsIndex = ...,
    m: typing.SupportsInt | typing.SupportsIndex = ...,
) -> Body: ...
def datetime_to_itime(*args, **kwargs): ...
def datetime_to_mjd(datetime: DateTime) -> float: ...
@overload
def decibel_to_decimal(x: Real) -> Real: ...
@overload
def decibel_to_decimal(
    x: typing.Annotated[numpy.typing.ArrayLike, Real, "[m, n]"],
) -> typing.Annotated[numpy.typing.NDArray[Real], "[m, n]"]: ...
@overload
def decimal_to_decibel(x: Real) -> Real: ...
@overload
def decimal_to_decibel(
    x: typing.Annotated[numpy.typing.ArrayLike, Real, "[m, n]"],
) -> typing.Annotated[numpy.typing.NDArray[Real], "[m, n]"]: ...
def deg_min_sec_to_degrees(
    hms: typing.Annotated[numpy.typing.ArrayLike, Real, "[3, 1]"],
) -> Real: ...
def degrees_to_deg_min_sec(deg: Real) -> typing.Annotated[numpy.typing.NDArray[Real], "[3, 1]"]: ...
@overload
def delaunay_to_classical(
    deloe: typing.Annotated[numpy.typing.ArrayLike, Real, "[6, 1]"], GM: Real
) -> typing.Annotated[numpy.typing.NDArray[Real], "[6, 1]"]: ...
@overload
def delaunay_to_classical(
    deloe: typing.Annotated[numpy.typing.ArrayLike, Real, "[6, 1]"],
    GM: typing.Annotated[numpy.typing.ArrayLike, Real, "[m, 1]"],
) -> typing.Annotated[numpy.typing.NDArray[Real], "[m, 6]"]: ...
@overload
def delaunay_to_classical(
    deloe: typing.Annotated[numpy.typing.ArrayLike, Real, "[m, 6]"], GM: Real
) -> typing.Annotated[numpy.typing.NDArray[Real], "[m, 6]"]: ...
@overload
def delaunay_to_classical(
    deloe: typing.Annotated[numpy.typing.ArrayLike, Real, "[m, 6]"],
    GM: typing.Annotated[numpy.typing.ArrayLike, Real, "[m, 1]"],
) -> typing.Annotated[numpy.typing.NDArray[Real], "[m, 6]"]: ...
@overload
def delaunay_to_classical(
    deloe: typing.Annotated[numpy.typing.ArrayLike, Real, "[6, 1]"], GM: Real
) -> typing.Annotated[numpy.typing.NDArray[Real], "[6, 1]"]: ...
@overload
def delaunay_to_classical(
    deloe: typing.Annotated[numpy.typing.ArrayLike, Real, "[6, 1]"],
    GM: typing.Annotated[numpy.typing.ArrayLike, Real, "[m, 1]"],
) -> typing.Annotated[numpy.typing.NDArray[Real], "[m, 6]"]: ...
@overload
def delaunay_to_classical(
    deloe: typing.Annotated[numpy.typing.ArrayLike, Real, "[m, 6]"], GM: Real
) -> typing.Annotated[numpy.typing.NDArray[Real], "[m, 6]"]: ...
@overload
def delaunay_to_classical(
    deloe: typing.Annotated[numpy.typing.ArrayLike, Real, "[m, 6]"],
    GM: typing.Annotated[numpy.typing.ArrayLike, Real, "[m, 1]"],
) -> typing.Annotated[numpy.typing.NDArray[Real], "[m, 6]"]: ...
@overload
def delaunay_to_classical(
    deloe: typing.Annotated[numpy.typing.ArrayLike, Real, "[6, 1]"], GM: Real
) -> typing.Annotated[numpy.typing.NDArray[Real], "[6, 1]"]: ...
@overload
def delaunay_to_classical(
    deloe: typing.Annotated[numpy.typing.ArrayLike, Real, "[6, 1]"],
    GM: typing.Annotated[numpy.typing.ArrayLike, Real, "[m, 1]"],
) -> typing.Annotated[numpy.typing.NDArray[Real], "[m, 6]"]: ...
@overload
def delaunay_to_classical(
    deloe: typing.Annotated[numpy.typing.ArrayLike, Real, "[m, 6]"], GM: Real
) -> typing.Annotated[numpy.typing.NDArray[Real], "[m, 6]"]: ...
@overload
def delaunay_to_classical(
    deloe: typing.Annotated[numpy.typing.ArrayLike, Real, "[m, 6]"],
    GM: typing.Annotated[numpy.typing.ArrayLike, Real, "[m, 1]"],
) -> typing.Annotated[numpy.typing.NDArray[Real], "[m, 6]"]: ...
@overload
def delaunay_to_classical(
    deloe: typing.Annotated[numpy.typing.ArrayLike, Real, "[6, 1]"], GM: Real
) -> typing.Annotated[numpy.typing.NDArray[Real], "[6, 1]"]: ...
@overload
def delaunay_to_classical(
    deloe: typing.Annotated[numpy.typing.ArrayLike, Real, "[6, 1]"],
    GM: typing.Annotated[numpy.typing.ArrayLike, Real, "[m, 1]"],
) -> typing.Annotated[numpy.typing.NDArray[Real], "[m, 6]"]: ...
@overload
def delaunay_to_classical(
    deloe: typing.Annotated[numpy.typing.ArrayLike, Real, "[m, 6]"], GM: Real
) -> typing.Annotated[numpy.typing.NDArray[Real], "[m, 6]"]: ...
@overload
def delaunay_to_classical(
    deloe: typing.Annotated[numpy.typing.ArrayLike, Real, "[m, 6]"],
    GM: typing.Annotated[numpy.typing.ArrayLike, Real, "[m, 1]"],
) -> typing.Annotated[numpy.typing.NDArray[Real], "[m, 6]"]: ...
@overload
def delaunay_to_classical(
    deloe: typing.Annotated[numpy.typing.ArrayLike, Real, "[6, 1]"], GM: Real
) -> typing.Annotated[numpy.typing.NDArray[Real], "[6, 1]"]: ...
@overload
def delaunay_to_classical(
    deloe: typing.Annotated[numpy.typing.ArrayLike, Real, "[6, 1]"],
    GM: typing.Annotated[numpy.typing.ArrayLike, Real, "[m, 1]"],
) -> typing.Annotated[numpy.typing.NDArray[Real], "[m, 6]"]: ...
@overload
def delaunay_to_classical(
    deloe: typing.Annotated[numpy.typing.ArrayLike, Real, "[m, 6]"], GM: Real
) -> typing.Annotated[numpy.typing.NDArray[Real], "[m, 6]"]: ...
@overload
def delaunay_to_classical(
    deloe: typing.Annotated[numpy.typing.ArrayLike, Real, "[m, 6]"],
    GM: typing.Annotated[numpy.typing.ArrayLike, Real, "[m, 1]"],
) -> typing.Annotated[numpy.typing.NDArray[Real], "[m, 6]"]: ...
@overload
def delaunay_to_classical(
    deloe: typing.Annotated[numpy.typing.ArrayLike, Real, "[6, 1]"], GM: Real
) -> typing.Annotated[numpy.typing.NDArray[Real], "[6, 1]"]: ...
@overload
def delaunay_to_classical(
    deloe: typing.Annotated[numpy.typing.ArrayLike, Real, "[6, 1]"],
    GM: typing.Annotated[numpy.typing.ArrayLike, Real, "[m, 1]"],
) -> typing.Annotated[numpy.typing.NDArray[Real], "[m, 6]"]: ...
@overload
def delaunay_to_classical(
    deloe: typing.Annotated[numpy.typing.ArrayLike, Real, "[m, 6]"], GM: Real
) -> typing.Annotated[numpy.typing.NDArray[Real], "[m, 6]"]: ...
@overload
def delaunay_to_classical(
    deloe: typing.Annotated[numpy.typing.ArrayLike, Real, "[m, 6]"],
    GM: typing.Annotated[numpy.typing.ArrayLike, Real, "[m, 1]"],
) -> typing.Annotated[numpy.typing.NDArray[Real], "[m, 6]"]: ...
@overload
def east_north_up_to_az_el_range(
    enu: typing.Annotated[numpy.typing.ArrayLike, Real, "[3, 1]"],
) -> typing.Annotated[numpy.typing.NDArray[Real], "[3, 1]"]: ...
@overload
def east_north_up_to_az_el_range(
    enu: typing.Annotated[numpy.typing.ArrayLike, Real, "[m, 3]"],
) -> typing.Annotated[numpy.typing.NDArray[Real], "[m, 3]"]: ...
@overload
def east_north_up_to_cart(
    enu: typing.Annotated[numpy.typing.ArrayLike, Real, "[3, 1]"],
    xyz_ref: typing.Annotated[numpy.typing.ArrayLike, Real, "[3, 1]"],
) -> typing.Annotated[numpy.typing.NDArray[Real], "[3, 1]"]: ...
@overload
def east_north_up_to_cart(
    enu: typing.Annotated[numpy.typing.ArrayLike, Real, "[m, 3]"],
    xyz_ref: typing.Annotated[numpy.typing.ArrayLike, Real, "[3, 1]"],
) -> typing.Annotated[numpy.typing.NDArray[Real], "[m, 3]"]: ...
@overload
def east_north_up_to_cart(
    enu: typing.Annotated[numpy.typing.ArrayLike, Real, "[3, 1]"],
    xyz_ref: typing.Annotated[numpy.typing.ArrayLike, Real, "[m, 3]"],
) -> typing.Annotated[numpy.typing.NDArray[Real], "[m, 3]"]: ...
@overload
def east_north_up_to_cart(
    enu: typing.Annotated[numpy.typing.ArrayLike, Real, "[m, 3]"],
    xyz_ref: typing.Annotated[numpy.typing.ArrayLike, Real, "[m, 3]"],
) -> typing.Annotated[numpy.typing.NDArray[Real], "[m, 3]"]: ...
def ecc2true(
    E: typing.SupportsFloat | typing.SupportsIndex, e: typing.SupportsFloat | typing.SupportsIndex
) -> float: ...
@overload
def eccentric_to_mean_anomaly(E: Real, e: Real) -> Real: ...
@overload
def eccentric_to_mean_anomaly(
    E: typing.Annotated[numpy.typing.ArrayLike, Real, "[m, 1]"], e: Real
) -> typing.Annotated[numpy.typing.NDArray[Real], "[m, 1]"]: ...
@overload
def eccentric_to_mean_anomaly(
    E: Real, e: typing.Annotated[numpy.typing.ArrayLike, Real, "[m, 1]"]
) -> typing.Annotated[numpy.typing.NDArray[Real], "[m, 1]"]: ...
@overload
def eccentric_to_mean_anomaly(
    E: typing.Annotated[numpy.typing.ArrayLike, Real, "[m, 1]"],
    e: typing.Annotated[numpy.typing.ArrayLike, Real, "[m, 1]"],
) -> typing.Annotated[numpy.typing.NDArray[Real], "[m, 1]"]: ...
@overload
def eccentric_to_true_anomaly(E: Real, e: Real) -> Real: ...
@overload
def eccentric_to_true_anomaly(
    E: typing.Annotated[numpy.typing.ArrayLike, Real, "[m, 1]"], e: Real
) -> typing.Annotated[numpy.typing.NDArray[Real], "[m, 1]"]: ...
@overload
def eccentric_to_true_anomaly(
    E: Real, e: typing.Annotated[numpy.typing.ArrayLike, Real, "[m, 1]"]
) -> typing.Annotated[numpy.typing.NDArray[Real], "[m, 1]"]: ...
@overload
def eccentric_to_true_anomaly(
    E: typing.Annotated[numpy.typing.ArrayLike, Real, "[m, 1]"],
    e: typing.Annotated[numpy.typing.ArrayLike, Real, "[m, 1]"],
) -> typing.Annotated[numpy.typing.NDArray[Real], "[m, 1]"]: ...
@overload
def equinoctial_to_classical(
    eqoe: typing.Annotated[numpy.typing.ArrayLike, Real, "[6, 1]"], GM: Real
) -> typing.Annotated[numpy.typing.NDArray[Real], "[6, 1]"]: ...
@overload
def equinoctial_to_classical(
    eqoe: typing.Annotated[numpy.typing.ArrayLike, Real, "[6, 1]"],
    GM: typing.Annotated[numpy.typing.ArrayLike, Real, "[m, 1]"],
) -> typing.Annotated[numpy.typing.NDArray[Real], "[m, 6]"]: ...
@overload
def equinoctial_to_classical(
    eqoe: typing.Annotated[numpy.typing.ArrayLike, Real, "[m, 6]"], GM: Real
) -> typing.Annotated[numpy.typing.NDArray[Real], "[m, 6]"]: ...
@overload
def equinoctial_to_classical(
    eqoe: typing.Annotated[numpy.typing.ArrayLike, Real, "[m, 6]"],
    GM: typing.Annotated[numpy.typing.ArrayLike, Real, "[m, 1]"],
) -> typing.Annotated[numpy.typing.NDArray[Real], "[m, 6]"]: ...
@overload
def equinoctial_to_classical(
    eqoe: typing.Annotated[numpy.typing.ArrayLike, Real, "[6, 1]"], GM: Real
) -> typing.Annotated[numpy.typing.NDArray[Real], "[6, 1]"]: ...
@overload
def equinoctial_to_classical(
    eqoe: typing.Annotated[numpy.typing.ArrayLike, Real, "[6, 1]"],
    GM: typing.Annotated[numpy.typing.ArrayLike, Real, "[m, 1]"],
) -> typing.Annotated[numpy.typing.NDArray[Real], "[m, 6]"]: ...
@overload
def equinoctial_to_classical(
    eqoe: typing.Annotated[numpy.typing.ArrayLike, Real, "[m, 6]"], GM: Real
) -> typing.Annotated[numpy.typing.NDArray[Real], "[m, 6]"]: ...
@overload
def equinoctial_to_classical(
    eqoe: typing.Annotated[numpy.typing.ArrayLike, Real, "[m, 6]"],
    GM: typing.Annotated[numpy.typing.ArrayLike, Real, "[m, 1]"],
) -> typing.Annotated[numpy.typing.NDArray[Real], "[m, 6]"]: ...
def find_file_in_dir(*args, **kwargs): ...
def gcpm_v24(
    datetime: DateTime,
    r_RE: typing.SupportsFloat | typing.SupportsIndex,
    amlt: typing.SupportsFloat | typing.SupportsIndex,
    alatr: typing.SupportsFloat | typing.SupportsIndex,
    akp: typing.SupportsFloat | typing.SupportsIndex = ...,
) -> list[float]: ...
def gcpm_v24_fortran(
    datetime: DateTime,
    r_RE: typing.SupportsFloat | typing.SupportsIndex,
    amlt: typing.SupportsFloat | typing.SupportsIndex,
    alatr: typing.SupportsFloat | typing.SupportsIndex,
    akp: typing.SupportsFloat | typing.SupportsIndex = ...,
) -> list[float]: ...
def get_ascii_kernel_dir() -> str: ...
@overload
def get_body_pos(
    t_tdb: Real, center: BodyId, target: BodyId, frame: Frame
) -> typing.Annotated[numpy.typing.NDArray[Real], "[3, 1]"]: ...
@overload
def get_body_pos(
    t_tdb: Real,
    center: BodyId,
    target: BodyId,
    frame: Frame,
    units: UnitSystem = ...,
    coordinate_scale: CoordinateScale = ...,
) -> typing.Annotated[numpy.typing.NDArray[Real], "[3, 1]"]: ...
@overload
def get_body_pos(
    t_tdb: Real, target: BodyId, frame: Frame
) -> typing.Annotated[numpy.typing.NDArray[Real], "[3, 1]"]: ...
@overload
def get_body_pos(
    t_tdb: Real,
    target: BodyId,
    frame: Frame,
    units: UnitSystem = ...,
    coordinate_scale: CoordinateScale = ...,
) -> typing.Annotated[numpy.typing.NDArray[Real], "[3, 1]"]: ...
@overload
def get_body_pos_vel(
    t_tdb: Real, center: BodyId, target: BodyId, frame: Frame
) -> typing.Annotated[numpy.typing.NDArray[Real], "[6, 1]"]: ...
@overload
def get_body_pos_vel(
    t_tdb: Real,
    center: BodyId,
    target: BodyId,
    frame: Frame,
    units: UnitSystem = ...,
    coordinate_scale: CoordinateScale = ...,
) -> typing.Annotated[numpy.typing.NDArray[Real], "[6, 1]"]: ...
@overload
def get_body_pos_vel(
    t_tdb: typing.Annotated[numpy.typing.ArrayLike, Real, "[m, 1]"],
    center: BodyId,
    target: BodyId,
    frame: Frame,
) -> typing.Annotated[numpy.typing.NDArray[Real], "[m, 6]"]: ...
@overload
def get_body_pos_vel(
    t_tdb: typing.Annotated[numpy.typing.ArrayLike, Real, "[m, 1]"],
    center: BodyId,
    target: BodyId,
    frame: Frame,
    units: UnitSystem = ...,
    coordinate_scale: CoordinateScale = ...,
) -> typing.Annotated[numpy.typing.NDArray[Real], "[m, 6]"]: ...
@overload
def get_body_pos_vel(
    t_tdb: Real, target: BodyId, frame: Frame
) -> typing.Annotated[numpy.typing.NDArray[Real], "[6, 1]"]: ...
@overload
def get_body_pos_vel(
    t_tdb: Real,
    target: BodyId,
    frame: Frame,
    units: UnitSystem = ...,
    coordinate_scale: CoordinateScale = ...,
) -> typing.Annotated[numpy.typing.NDArray[Real], "[6, 1]"]: ...
@overload
def get_body_pos_vel(
    t_tdb: typing.Annotated[numpy.typing.ArrayLike, Real, "[m, 1]"], target: BodyId, frame: Frame
) -> typing.Annotated[numpy.typing.NDArray[Real], "[m, 6]"]: ...
@overload
def get_body_pos_vel(
    t_tdb: typing.Annotated[numpy.typing.ArrayLike, Real, "[m, 1]"],
    target: BodyId,
    frame: Frame,
    units: UnitSystem = ...,
    coordinate_scale: CoordinateScale = ...,
) -> typing.Annotated[numpy.typing.NDArray[Real], "[m, 6]"]: ...
def get_cspice_kernel_dir() -> str: ...
def get_data_path() -> str: ...
def get_eop_data(mjd_utc: Real) -> dict: ...
def get_eop_file_data() -> dict: ...
def get_file_path(arg0: str) -> str: ...
def get_frame_center(frame: Frame) -> BodyId: ...
def get_frame_rotation_translation(t_tdb: Real, frame_in: Frame, frame_out: Frame) -> tuple[
    typing.Annotated[numpy.typing.NDArray[Real], "[3, 3]"],
    typing.Annotated[numpy.typing.NDArray[Real], "[3, 1]"],
]: ...
def get_frame_rotation_translation_rv(t_tdb: Real, frame_in: Frame, frame_out: Frame) -> tuple[
    typing.Annotated[numpy.typing.NDArray[Real], "[6, 6]"],
    typing.Annotated[numpy.typing.NDArray[Real], "[6, 1]"],
]: ...
def get_iono_params(
    t_j2000: typing.SupportsFloat | typing.SupportsIndex,
    kp: typing.SupportsFloat | typing.SupportsIndex = ...,
) -> typing.Annotated[numpy.typing.NDArray[numpy.float64], "[3, 1]"]: ...
def get_iri_model() -> str: ...
def get_kp_index(datetime: DateTime) -> float: ...
def get_lunar_orientation_angles(
    t_tdb: typing.SupportsFloat | typing.SupportsIndex,
) -> typing.Annotated[numpy.typing.NDArray[numpy.float64], "[6, 1]"]: ...
def get_lupnt_epoch() -> Real: ...
@overload
def get_orbital_period(a: Real, GM: Real) -> Real: ...
@overload
def get_orbital_period(
    a: typing.Annotated[numpy.typing.ArrayLike, Real, "[m, 1]"], GM: Real
) -> typing.Annotated[numpy.typing.NDArray[Real], "[m, 1]"]: ...
@overload
def get_orbital_period(
    a: Real, GM: typing.Annotated[numpy.typing.ArrayLike, Real, "[m, 1]"]
) -> typing.Annotated[numpy.typing.NDArray[Real], "[m, 1]"]: ...
@overload
def get_orbital_period(
    a: typing.Annotated[numpy.typing.ArrayLike, Real, "[m, 1]"],
    GM: typing.Annotated[numpy.typing.ArrayLike, Real, "[m, 1]"],
) -> typing.Annotated[numpy.typing.NDArray[Real], "[m, 1]"]: ...
def get_output_dir(arg0: str) -> str: ...
@overload
def get_physical_constants(units: UnitSystem = ...) -> PhysicalConstants: ...
@overload
def get_physical_constants(units: UnitSystem, coordinate_scale) -> PhysicalConstants: ...
@overload
def get_physical_constants(coordinate_scale) -> PhysicalConstants: ...
def get_plasma_base_path() -> str: ...
@overload
def get_proper_time_correction_tcl(
    t_tcg: Real, x_mci: typing.Annotated[numpy.typing.ArrayLike, Real, "[3, 1]"]
) -> Real: ...
@overload
def get_proper_time_correction_tcl(
    t_tcg: typing.Annotated[numpy.typing.ArrayLike, Real, "[m, 1]"],
    x_mci: typing.Annotated[numpy.typing.ArrayLike, Real, "[m, n]"],
) -> typing.Annotated[numpy.typing.NDArray[Real], "[m, 1]"]: ...
@overload
def gregorian_to_mjd(
    year: typing.SupportsInt | typing.SupportsIndex,
    month: typing.SupportsInt | typing.SupportsIndex,
    day: typing.SupportsInt | typing.SupportsIndex,
    hour: typing.SupportsInt | typing.SupportsIndex,
    min: typing.SupportsInt | typing.SupportsIndex,
    sec: Real,
) -> Real: ...
@overload
def gregorian_to_mjd(
    year: typing.SupportsInt | typing.SupportsIndex,
    month: typing.SupportsInt | typing.SupportsIndex,
    day: typing.SupportsInt | typing.SupportsIndex,
    hour: typing.SupportsInt | typing.SupportsIndex = ...,
    min: typing.SupportsInt | typing.SupportsIndex = ...,
    sec: typing.SupportsFloat | typing.SupportsIndex = ...,
) -> float: ...
@overload
def gregorian_to_time(
    year: typing.SupportsInt | typing.SupportsIndex,
    month: typing.SupportsInt | typing.SupportsIndex,
    day: typing.SupportsInt | typing.SupportsIndex,
    hour: typing.SupportsInt | typing.SupportsIndex,
    min: typing.SupportsInt | typing.SupportsIndex,
    sec: Real,
) -> Real: ...
@overload
def gregorian_to_time(date: str) -> Real: ...
def init_default_config_search_dirs() -> None: ...
def is_coordinate_time_scale(time: Time) -> bool: ...
def itime_to_datetime(itime) -> DateTime: ...
@overload
def lat_lon_alt_to_cart(
    lla: typing.Annotated[numpy.typing.ArrayLike, Real, "[3, 1]"], R_body: Real
) -> typing.Annotated[numpy.typing.NDArray[Real], "[3, 1]"]: ...
@overload
def lat_lon_alt_to_cart(
    lla: typing.Annotated[numpy.typing.ArrayLike, Real, "[3, 1]"],
    R_body: typing.Annotated[numpy.typing.ArrayLike, Real, "[m, 1]"],
) -> typing.Annotated[numpy.typing.NDArray[Real], "[m, 3]"]: ...
@overload
def lat_lon_alt_to_cart(
    lla: typing.Annotated[numpy.typing.ArrayLike, Real, "[m, 3]"], R_body: Real
) -> typing.Annotated[numpy.typing.NDArray[Real], "[m, 3]"]: ...
@overload
def lat_lon_alt_to_cart(
    lla: typing.Annotated[numpy.typing.ArrayLike, Real, "[m, 3]"],
    R_body: typing.Annotated[numpy.typing.ArrayLike, Real, "[m, 1]"],
) -> typing.Annotated[numpy.typing.NDArray[Real], "[m, 3]"]: ...
@overload
def lat_lon_alt_to_stereographic(
    lla: typing.Annotated[numpy.typing.ArrayLike, Real, "[3, 1]"], R_body: Real
) -> typing.Annotated[numpy.typing.NDArray[Real], "[3, 1]"]: ...
@overload
def lat_lon_alt_to_stereographic(
    lla: typing.Annotated[numpy.typing.ArrayLike, Real, "[3, 1]"],
    R_body: typing.Annotated[numpy.typing.ArrayLike, Real, "[m, 1]"],
) -> typing.Annotated[numpy.typing.NDArray[Real], "[m, 3]"]: ...
@overload
def lat_lon_alt_to_stereographic(
    lla: typing.Annotated[numpy.typing.ArrayLike, Real, "[m, 3]"], R_body: Real
) -> typing.Annotated[numpy.typing.NDArray[Real], "[m, 3]"]: ...
@overload
def lat_lon_alt_to_stereographic(
    lla: typing.Annotated[numpy.typing.ArrayLike, Real, "[m, 3]"],
    R_body: typing.Annotated[numpy.typing.ArrayLike, Real, "[m, 1]"],
) -> typing.Annotated[numpy.typing.NDArray[Real], "[m, 3]"]: ...
@overload
def load_config(path: str, key: str = ..., recursive: bool = ...) -> Config: ...
@overload
def load_config(config: dict) -> Config: ...
@overload
def load_config(config: Config) -> Config: ...
def load_eop_file_data(filepath: str, force: bool = ...) -> None: ...
def load_latest_eop_from_iers(force: bool = ...) -> bool: ...
def load_tiff(path, xlims, ylims, max_res: typing.SupportsFloat | typing.SupportsIndex) -> tuple[
    typing.Annotated[numpy.typing.NDArray[numpy.float64], "[m, n]"],
    typing.Annotated[numpy.typing.NDArray[numpy.float64], "[m, n]"],
    typing.Annotated[numpy.typing.NDArray[numpy.float64], "[m, n]"],
]: ...
def long_to_lt(longitude: typing.SupportsFloat | typing.SupportsIndex) -> float: ...
def lt_to_long(amlt: typing.SupportsFloat | typing.SupportsIndex) -> float: ...
def mean2ecc(
    M: typing.SupportsFloat | typing.SupportsIndex, e: typing.SupportsFloat | typing.SupportsIndex
) -> float: ...
def mean2true(
    M: typing.SupportsFloat | typing.SupportsIndex, e: typing.SupportsFloat | typing.SupportsIndex
) -> float: ...
@overload
def mean_to_eccentric_anomaly(M: Real, e: Real) -> Real: ...
@overload
def mean_to_eccentric_anomaly(
    M: typing.Annotated[numpy.typing.ArrayLike, Real, "[m, 1]"], e: Real
) -> typing.Annotated[numpy.typing.NDArray[Real], "[m, 1]"]: ...
@overload
def mean_to_eccentric_anomaly(
    M: Real, e: typing.Annotated[numpy.typing.ArrayLike, Real, "[m, 1]"]
) -> typing.Annotated[numpy.typing.NDArray[Real], "[m, 1]"]: ...
@overload
def mean_to_eccentric_anomaly(
    M: typing.Annotated[numpy.typing.ArrayLike, Real, "[m, 1]"],
    e: typing.Annotated[numpy.typing.ArrayLike, Real, "[m, 1]"],
) -> typing.Annotated[numpy.typing.NDArray[Real], "[m, 1]"]: ...
@overload
def mean_to_true_anomaly(M: Real, e: Real) -> Real: ...
@overload
def mean_to_true_anomaly(
    M: typing.Annotated[numpy.typing.ArrayLike, Real, "[m, 1]"], e: Real
) -> typing.Annotated[numpy.typing.NDArray[Real], "[m, 1]"]: ...
@overload
def mean_to_true_anomaly(
    M: Real, e: typing.Annotated[numpy.typing.ArrayLike, Real, "[m, 1]"]
) -> typing.Annotated[numpy.typing.NDArray[Real], "[m, 1]"]: ...
@overload
def mean_to_true_anomaly(
    M: typing.Annotated[numpy.typing.ArrayLike, Real, "[m, 1]"],
    e: typing.Annotated[numpy.typing.ArrayLike, Real, "[m, 1]"],
) -> typing.Annotated[numpy.typing.NDArray[Real], "[m, 1]"]: ...
def mjd_to_datetime(mjd: typing.SupportsFloat | typing.SupportsIndex) -> DateTime: ...
def mjd_to_gregorian(mjd: Real) -> tuple[int, int, int, int, int, Real]: ...
def mjd_to_gregorian_string(
    mjd: Real, precision: typing.SupportsInt | typing.SupportsIndex = ...
) -> str: ...
def mjd_to_time(mjd: Real) -> Real: ...
def mjd_to_tj2000(mjd: typing.SupportsFloat | typing.SupportsIndex) -> float: ...
@overload
def normalize_quat(
    qw: typing.Annotated[numpy.typing.ArrayLike, Real, "[4, 1]"],
) -> typing.Annotated[numpy.typing.NDArray[Real], "[4, 1]"]: ...
@overload
def normalize_quat(
    qw: typing.Annotated[numpy.typing.ArrayLike, Real, "[m, 4]"],
) -> typing.Annotated[numpy.typing.NDArray[Real], "[m, 4]"]: ...
def propagate_coe(
    coe: typing.Annotated[numpy.typing.ArrayLike, numpy.float64, "[6, 1]"],
    GM: typing.SupportsFloat | typing.SupportsIndex,
    dt: typing.SupportsFloat | typing.SupportsIndex,
) -> typing.Annotated[numpy.typing.NDArray[numpy.float64], "[6, 1]"]: ...
@overload
def quasi_nonsingular_to_classical(
    qnsoe: typing.Annotated[numpy.typing.ArrayLike, Real, "[6, 1]"], GM: Real
) -> typing.Annotated[numpy.typing.NDArray[Real], "[6, 1]"]: ...
@overload
def quasi_nonsingular_to_classical(
    qnsoe: typing.Annotated[numpy.typing.ArrayLike, Real, "[6, 1]"],
    GM: typing.Annotated[numpy.typing.ArrayLike, Real, "[m, 1]"],
) -> typing.Annotated[numpy.typing.NDArray[Real], "[m, 6]"]: ...
@overload
def quasi_nonsingular_to_classical(
    qnsoe: typing.Annotated[numpy.typing.ArrayLike, Real, "[m, 6]"], GM: Real
) -> typing.Annotated[numpy.typing.NDArray[Real], "[m, 6]"]: ...
@overload
def quasi_nonsingular_to_classical(
    qnsoe: typing.Annotated[numpy.typing.ArrayLike, Real, "[m, 6]"],
    GM: typing.Annotated[numpy.typing.ArrayLike, Real, "[m, 1]"],
) -> typing.Annotated[numpy.typing.NDArray[Real], "[m, 6]"]: ...
@overload
def quasi_nonsingular_to_classical(
    qnsoe: typing.Annotated[numpy.typing.ArrayLike, Real, "[6, 1]"], GM: Real
) -> typing.Annotated[numpy.typing.NDArray[Real], "[6, 1]"]: ...
@overload
def quasi_nonsingular_to_classical(
    qnsoe: typing.Annotated[numpy.typing.ArrayLike, Real, "[6, 1]"],
    GM: typing.Annotated[numpy.typing.ArrayLike, Real, "[m, 1]"],
) -> typing.Annotated[numpy.typing.NDArray[Real], "[m, 6]"]: ...
@overload
def quasi_nonsingular_to_classical(
    qnsoe: typing.Annotated[numpy.typing.ArrayLike, Real, "[m, 6]"], GM: Real
) -> typing.Annotated[numpy.typing.NDArray[Real], "[m, 6]"]: ...
@overload
def quasi_nonsingular_to_classical(
    qnsoe: typing.Annotated[numpy.typing.ArrayLike, Real, "[m, 6]"],
    GM: typing.Annotated[numpy.typing.ArrayLike, Real, "[m, 1]"],
) -> typing.Annotated[numpy.typing.NDArray[Real], "[m, 6]"]: ...
def quat_to_rot(
    qw: typing.Annotated[numpy.typing.ArrayLike, Real, "[m, 1]"],
) -> typing.Annotated[numpy.typing.NDArray[Real], "[3, 3]"]: ...
def refractive_index_neB(
    ne_m3: typing.SupportsFloat | typing.SupportsIndex,
    freq_Hz: typing.SupportsFloat | typing.SupportsIndex,
    B: typing.SupportsFloat | typing.SupportsIndex = ...,
    cos_theta: typing.SupportsFloat | typing.SupportsIndex = ...,
    compute_higher_order: bool = ...,
) -> float: ...
def roll_pitch_yaw_to_rot(
    rpy: typing.Annotated[numpy.typing.ArrayLike, Real, "[3, 1]"],
) -> typing.Annotated[numpy.typing.NDArray[Real], "[3, 3]"]: ...
def rot_to_quat(
    rot: typing.Annotated[numpy.typing.ArrayLike, Real, "[3, 3]"],
) -> typing.Annotated[numpy.typing.NDArray[Real], "[m, 1]"]: ...
def rot_to_roll_pitch_yaw(
    rot: typing.Annotated[numpy.typing.ArrayLike, Real, "[3, 3]"],
) -> typing.Annotated[numpy.typing.NDArray[Real], "[3, 1]"]: ...
def rot_x(angle: Real) -> typing.Annotated[numpy.typing.NDArray[Real], "[3, 3]"]: ...
def rot_y(angle: Real) -> typing.Annotated[numpy.typing.NDArray[Real], "[3, 3]"]: ...
def rot_z(angle: Real) -> typing.Annotated[numpy.typing.NDArray[Real], "[3, 3]"]: ...
def rotation_angle(R: typing.Annotated[numpy.typing.ArrayLike, Real, "[3, 3]"]) -> Real: ...
def save_config(config: Config, path: str) -> None: ...
@overload
def scalar_first_to_last(
    qw: typing.Annotated[numpy.typing.ArrayLike, Real, "[4, 1]"],
) -> typing.Annotated[numpy.typing.NDArray[Real], "[4, 1]"]: ...
@overload
def scalar_first_to_last(
    qw: typing.Annotated[numpy.typing.ArrayLike, Real, "[m, 4]"],
) -> typing.Annotated[numpy.typing.NDArray[Real], "[m, 4]"]: ...
@overload
def scalar_last_to_first(
    qw: typing.Annotated[numpy.typing.ArrayLike, Real, "[4, 1]"],
) -> typing.Annotated[numpy.typing.NDArray[Real], "[4, 1]"]: ...
@overload
def scalar_last_to_first(
    qw: typing.Annotated[numpy.typing.ArrayLike, Real, "[m, 4]"],
) -> typing.Annotated[numpy.typing.NDArray[Real], "[m, 4]"]: ...
def scale_gm_for_coordinate_scale(
    value: typing.SupportsFloat | typing.SupportsIndex, _from: CoordinateScale, to: CoordinateScale
) -> float: ...
def scale_length_for_coordinate_scale(
    value: typing.SupportsFloat | typing.SupportsIndex, _from: CoordinateScale, to: CoordinateScale
) -> float: ...
def set_iri2007_option(option: IRI2007Option) -> None: ...
def set_iri2020_option(option: IRI2020Option) -> None: ...
def set_iri_model(model_name: str = ...) -> None: ...
def set_lupnt_epoch(arg0: Real) -> None: ...
def set_plasma_base_path(path: str) -> None: ...
def setup_gnss_constellation(filename: str) -> list[Satellite]: ...
def skew(
    x: typing.Annotated[numpy.typing.ArrayLike, Real, "[3, 1]"],
) -> typing.Annotated[numpy.typing.NDArray[Real], "[3, 3]"]: ...
def solve_lt(
    sat: Satellite,
    rx_pos: typing.Annotated[numpy.typing.ArrayLike, numpy.float64, "[3, 1]"],
    epoch_utc_rx: typing.SupportsFloat | typing.SupportsIndex,
) -> typing.Annotated[numpy.typing.NDArray[numpy.float64], "[3, 1]"]: ...
@overload
def stereographic_to_cart(
    xya: typing.Annotated[numpy.typing.ArrayLike, Real, "[3, 1]"], R_body: Real
) -> typing.Annotated[numpy.typing.NDArray[Real], "[3, 1]"]: ...
@overload
def stereographic_to_cart(
    xya: typing.Annotated[numpy.typing.ArrayLike, Real, "[3, 1]"],
    R_body: typing.Annotated[numpy.typing.ArrayLike, Real, "[m, 1]"],
) -> typing.Annotated[numpy.typing.NDArray[Real], "[m, 3]"]: ...
@overload
def stereographic_to_cart(
    xya: typing.Annotated[numpy.typing.ArrayLike, Real, "[m, 3]"], R_body: Real
) -> typing.Annotated[numpy.typing.NDArray[Real], "[m, 3]"]: ...
@overload
def stereographic_to_cart(
    xya: typing.Annotated[numpy.typing.ArrayLike, Real, "[m, 3]"],
    R_body: typing.Annotated[numpy.typing.ArrayLike, Real, "[m, 1]"],
) -> typing.Annotated[numpy.typing.NDArray[Real], "[m, 3]"]: ...
@overload
def stereographic_to_lat_lon_alt(
    xya: typing.Annotated[numpy.typing.ArrayLike, Real, "[3, 1]"], R_body: Real
) -> typing.Annotated[numpy.typing.NDArray[Real], "[3, 1]"]: ...
@overload
def stereographic_to_lat_lon_alt(
    xya: typing.Annotated[numpy.typing.ArrayLike, Real, "[3, 1]"],
    R_body: typing.Annotated[numpy.typing.ArrayLike, Real, "[m, 1]"],
) -> typing.Annotated[numpy.typing.NDArray[Real], "[m, 3]"]: ...
@overload
def stereographic_to_lat_lon_alt(
    xya: typing.Annotated[numpy.typing.ArrayLike, Real, "[m, 3]"], R_body: Real
) -> typing.Annotated[numpy.typing.NDArray[Real], "[m, 3]"]: ...
@overload
def stereographic_to_lat_lon_alt(
    xya: typing.Annotated[numpy.typing.ArrayLike, Real, "[m, 3]"],
    R_body: typing.Annotated[numpy.typing.ArrayLike, Real, "[m, 1]"],
) -> typing.Annotated[numpy.typing.NDArray[Real], "[m, 3]"]: ...
@overload
def tcb_to_tcl(t_tcb: Real) -> Real: ...
@overload
def tcb_to_tcl(
    t_tcb: Real, x_bcrs: typing.Annotated[numpy.typing.ArrayLike, Real, "[3, 1]"]
) -> Real: ...
@overload
def tcb_to_tcl(
    t_tcb: typing.Annotated[numpy.typing.ArrayLike, Real, "[m, 1]"],
) -> typing.Annotated[numpy.typing.NDArray[Real], "[m, 1]"]: ...
@overload
def tcb_to_tcl(
    t_tcb: typing.Annotated[numpy.typing.ArrayLike, Real, "[m, 1]"],
    x_bcrs: typing.Annotated[numpy.typing.ArrayLike, Real, "[m, 3]"],
) -> typing.Annotated[numpy.typing.NDArray[Real], "[m, 1]"]: ...
@overload
def tcl_to_tcb(t_tcl: Real) -> Real: ...
@overload
def tcl_to_tcb(
    t_tcl: Real, x_bcrs: typing.Annotated[numpy.typing.ArrayLike, Real, "[3, 1]"]
) -> Real: ...
@overload
def tcl_to_tcb(
    t_tcl: typing.Annotated[numpy.typing.ArrayLike, Real, "[m, 1]"],
) -> typing.Annotated[numpy.typing.NDArray[Real], "[m, 1]"]: ...
@overload
def tcl_to_tcb(
    t_tcl: typing.Annotated[numpy.typing.ArrayLike, Real, "[m, 1]"],
    x_bcrs: typing.Annotated[numpy.typing.ArrayLike, Real, "[m, 3]"],
) -> typing.Annotated[numpy.typing.NDArray[Real], "[m, 1]"]: ...
def time_to_gregorian_string(
    t: Real, precision: typing.SupportsInt | typing.SupportsIndex = ...
) -> str: ...
def time_to_mjd(t: Real) -> Real: ...
def tj2000_to_mjd(t_j2000: typing.SupportsFloat | typing.SupportsIndex) -> float: ...
def tle_to_classical(
    arg0, arg1: Real
) -> typing.Annotated[numpy.typing.NDArray[Real], "[m, 1]"]: ...
def trace_ray(
    epoch: typing.SupportsFloat | typing.SupportsIndex,
    pos_tx: typing.Annotated[numpy.typing.ArrayLike, numpy.float64, "[3, 1]"],
    pos_rx: typing.Annotated[numpy.typing.ArrayLike, numpy.float64, "[3, 1]"],
    config: RayTraceConfig,
    debug_prop: bool = ...,
    debug_corr: bool = ...,
) -> PathProfile: ...
def true2mean(
    nu: typing.SupportsFloat | typing.SupportsIndex, e: typing.SupportsFloat | typing.SupportsIndex
) -> float: ...
@overload
def true_to_eccentric_anomaly(nu: Real, e: Real) -> Real: ...
@overload
def true_to_eccentric_anomaly(
    nu: typing.Annotated[numpy.typing.ArrayLike, Real, "[m, 1]"], e: Real
) -> typing.Annotated[numpy.typing.NDArray[Real], "[m, 1]"]: ...
@overload
def true_to_eccentric_anomaly(
    nu: Real, e: typing.Annotated[numpy.typing.ArrayLike, Real, "[m, 1]"]
) -> typing.Annotated[numpy.typing.NDArray[Real], "[m, 1]"]: ...
@overload
def true_to_eccentric_anomaly(
    nu: typing.Annotated[numpy.typing.ArrayLike, Real, "[m, 1]"],
    e: typing.Annotated[numpy.typing.ArrayLike, Real, "[m, 1]"],
) -> typing.Annotated[numpy.typing.NDArray[Real], "[m, 1]"]: ...
@overload
def true_to_mean_anomaly(f: Real, e: Real) -> Real: ...
@overload
def true_to_mean_anomaly(
    f: typing.Annotated[numpy.typing.ArrayLike, Real, "[m, 1]"], e: Real
) -> typing.Annotated[numpy.typing.NDArray[Real], "[m, 1]"]: ...
@overload
def true_to_mean_anomaly(
    f: Real, e: typing.Annotated[numpy.typing.ArrayLike, Real, "[m, 1]"]
) -> typing.Annotated[numpy.typing.NDArray[Real], "[m, 1]"]: ...
@overload
def true_to_mean_anomaly(
    f: typing.Annotated[numpy.typing.ArrayLike, Real, "[m, 1]"],
    e: typing.Annotated[numpy.typing.ArrayLike, Real, "[m, 1]"],
) -> typing.Annotated[numpy.typing.NDArray[Real], "[m, 1]"]: ...
def wrap2pi(angle: typing.SupportsFloat | typing.SupportsIndex) -> float: ...
@overload
def wrap_to_pi(angle: Real) -> Real: ...
@overload
def wrap_to_pi(
    angle: typing.Annotated[numpy.typing.ArrayLike, Real, "[m, 1]"],
) -> typing.Annotated[numpy.typing.NDArray[Real], "[m, 1]"]: ...
@overload
def wrap_to_two_pi(angle: Real) -> Real: ...
@overload
def wrap_to_two_pi(
    angle: typing.Annotated[numpy.typing.ArrayLike, Real, "[m, 1]"],
) -> typing.Annotated[numpy.typing.NDArray[Real], "[m, 1]"]: ...
