#!/usr/bin/env python
"""Install (or refresh) the ``lupnt`` Jupyter kernel for the pixi environment.

VS Code and Jupyter launch a kernel's interpreter *directly*, without running pixi's
activation, so the activation env vars (``PYTHONPATH`` -> ``python/``, ``LUPNT_DATA_PATH``,
...) are never set and the kernel cannot ``import pylupnt`` or locate ``LuPNT_data``. This
script makes the notebooks work through *both* ways VS Code can start a kernel:

1. A **kernelspec** named ``lupnt`` ("LuPNT (pixi)") with those env vars baked into its
   ``env`` block -- used when you pick it under "Select Another Kernel -> Jupyter Kernel".
2. A workspace **``.env``** file -- VS Code auto-loads ``${workspaceFolder}/.env`` and
   applies it to a kernel started from a plain interpreter, so selecting the pixi
   interpreter under "Python Environments" works too.

All paths are derived from this file's location, so it is correct per-machine and on both
macOS and Linux/WSL -- ``KernelSpecManager(user=True)`` writes to the platform's own Jupyter
data dir (``~/Library/Jupyter`` on macOS, ``~/.local/share/jupyter`` on Linux). The kernel's
interpreter is the stable project-local pixi symlink (``.pixi/envs/default/bin/python``),
not the hashed rattler-cache path, so it survives ``pixi install`` re-resolving the env.
Re-run after moving the repo or switching machines:

    pixi run install-kernel
"""

import json
import sys
import tempfile
from pathlib import Path

from jupyter_client.kernelspec import KernelSpecManager

# scripts/ is one level below the repo root.
ROOT = Path(__file__).resolve().parents[1]

# Prefer the stable project-local pixi interpreter symlink over sys.executable (which is the
# hashed rattler-cache path that changes when the env is re-solved). Fall back to whatever is
# running this script if the symlink is absent (e.g. a non-pixi invocation).
_symlink = (
    ROOT
    / ".pixi"
    / "envs"
    / "default"
    / "bin"
    / ("python.exe" if sys.platform == "win32" else "python")
)
INTERPRETER = str(_symlink if _symlink.exists() else Path(sys.executable))

# Mirrors the [activation].env block in pixi.toml.
ENV = {
    "PYTHONPATH": str(ROOT / "python"),
    "LUPNT_DATA_PATH": str(ROOT / "data" / "LuPNT_data"),
    "PECSIMPY_BASE_PATH": str(ROOT / "data" / "LuPNT_data" / "plasma"),
    "LUPNT_OUTPUT_PATH": str(ROOT / "output"),
}

KERNEL_NAME = "lupnt"
SPEC = {
    "argv": [
        INTERPRETER,
        "-Xfrozen_modules=off",
        "-m",
        "ipykernel_launcher",
        "-f",
        "{connection_file}",
    ],
    "display_name": "LuPNT (pixi)",
    "language": "python",
    "metadata": {"debugger": True},
    "env": ENV,
}


def write_env_file() -> Path:
    """Write ${repo}/.env so VS Code applies the same vars to interpreter-launched kernels."""
    env_path = ROOT / ".env"
    lines = [
        "# Generated by scripts/install_kernel.py (pixi run install-kernel). Git-ignored.",
        "# Lets VS Code run the LuPNT notebooks with the pixi interpreter selected directly.",
    ]
    lines += [f"{key}={value}" for key, value in ENV.items()]
    env_path.write_text("\n".join(lines) + "\n")
    return env_path


def main() -> None:
    with tempfile.TemporaryDirectory() as tmp:
        (Path(tmp) / "kernel.json").write_text(json.dumps(SPEC, indent=1))
        dest = KernelSpecManager().install_kernel_spec(tmp, kernel_name=KERNEL_NAME, user=True)
    env_path = write_env_file()
    print(f"Installed '{KERNEL_NAME}' kernel ({SPEC['display_name']}) -> {dest}")
    print(f"  interpreter: {INTERPRETER}")
    print(f"  wrote env file: {env_path}")
    for key, value in ENV.items():
        print(f"  {key} = {value}")


if __name__ == "__main__":
    main()
