# Project information
site_name: lupnt
site_description: lupnt documentation.
site_author: Allan leal
site_url: https://lupnt.github.io

# Repository
repo_name: lupnt/lupnt
repo_url: https://github.com/Stanford-NavLab/LuPNT/

# Copyright
copyright: 'Copyright &copy; 2018–2024 Stanford Navigation and Autonomous Vehicles (NAV) Lab'

# Configuration
theme:
  name: material
  palette:
    primary: 'teal'
    accent: 'pink'
  favicon: 'img/lupnt-logo.svg'
  logo: 'img/lupnt-logo.svg'

# Path where the markdown files are
docs_dir: 'website'

# Navigation
nav:
  - Home: index.md
  - Installation: installation.md
  - Tutorials: tutorials.md
  - FAQ: faq.md
  - About: about.md

# Customization
extra_css:
    - css/extra.css

# Extensions
markdown_extensions:
  - admonition
  - attr_list
  - toc:
      permalink: true
  - pymdownx.arithmatex
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.caret
  - pymdownx.critic
  - pymdownx.details
  - pymdownx.emoji:
      emoji_generator: !!python/name:pymdownx.emoji.to_svg
  - pymdownx.inlinehilite
  - pymdownx.magiclink
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.superfences
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tilde

# Plugins
plugins:
  - search
  - macros:
      module_name: mkdocs-macros

# Macros
extra:
  lupnt: <span style="font-family:'Comfortaa'">lupnt</span>
