blue_dataset:
  class: BlueOriginDataset
  data_dir: "data/BlueOrigin/delivery_v3/data1"
  map_path: "data/BlueOrigin/delivery_v3/data1/dem.npy"

  start_frame: 0
  end_frame: -1
  frame_rate: 1.0 # [Hz]
  step: 1

  intrinsics:
    fx: 958.1986162499028 # [px] Focal length
    fy: 958.1986162499028 # [px] Focal length
    H: 1000 # [px] Image height
    W: 1000 # [px] Image width
