lusnar_dataset:
  class: LuSNARDataset
  base_dir: data/LuSNAR/
  scene: 9

  dem_file: lusnar_dem_1mpp.npy
  dem_xlims: [-38.879454709875205, 295.8301103506405]  # [m]
  dem_ylims: [-181.90757578089267, 292.38608059260264]  # [m]
  dem_res: 1.0  # [m]

  # Dataset parameters
  max_depth: 10000.0
  downsample_img: 2
  downsample_lidar: 1
  baseline: 0.310

  # Map
  voxel_size: 0.001 # [m]
  use_lidar: True
  use_depth: True

  # Data loading parameters
  data: ["rgb_left", "rgb_right", "depth", "label", "lidar"]
  # Either number of frames (int) or fraction (float)
  start: 0.0
  step: 1
  end: 1.0
  num_workers: 20
  dtype: "float32"
  shuffle: False
  seed: 231
  preload: "none"

  # Camera intrinsics
  intrinsics:
    H: 1024
    W: 1024
    fovx: 1.3962634016
    fovy: 1.3962634016

  # IMU
  q_imu: [0.0, 0.0, 0.0, 1.0] # [qx, qy, qz, qw]
  T_imu: [1.0, 0.0, -1.5]

  # LiDAR
  q_lidar: [0.0, 0.0, 0.0, 1.0]
  T_lidar: [1.0, 0.0, -1.5]

  # Front left
  q_left: [0.406, 0.406, 0.579, 0.579]
  T_left: [1.0, -0.155, -1.500]

  # Front right
  q_right: [0.406, 0.406, 0.579, 0.579]
  T_right: [1.0, 0.155, -1.500]
