open3d_dataset:
  class: Open3DDataset
  environment:
    inherit_from: open3d_environment.yaml::open3d_small

  waypoints:
    - [+18, -10]
    - [-22, 0]
    - [-18, 8]
    - [+23, 5]
  dist_keep_out: 2.0 # [m]
  close: true
  repeat: 1
  min_dist: 1.0 # [m]
  smooth_s: 2
  smooth_k: 3
  astar_resolution: 0.4 # [m]
