name: Docs

on:
  push:
    branches:
      - master
      - main
      - guillemc
  pull_request:
    branches:
      - master
      - main

env:
  CPM_SOURCE_CACHE: ${{ github.workspace }}/cpm_modules

jobs:
  build-docs:
    name: Build and publish documentation
    runs-on: macos-latest
    steps:
      - name: Install OpenMP
        run: brew install libomp

      - uses: actions/checkout@v3

      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"
          allow-prereleases: true

      - uses: actions/cache@v3
        with:
          path: "**/cpm_modules"
          key: ${{ github.workflow }}-cpm-modules-${{ hashFiles('**/CMakeLists.txt', '**/*.cmake') }}

      - name: cache LuPNT_data
        id: cache-lupnt
        uses: actions/cache@v3
        with:
          path: data
          key: LuPNT_data-${{ vars.LUPNT_DATA_CACHE_DATE }}

      - name: download and unzip LuPNT_data
        if: steps.cache-lupnt.outputs.cache-hit != 'true'
        run: |
          curl -L https://bit.ly/LuPNT_data -o LuPNT_data.zip
          unzip LuPNT_data.zip
          rm LuPNT_data.zip

      - name: Install pylupnt
        run: |
          python -m pip install . -v

      - name: Install dependencies
        run: |
          cd docs
          brew install doxygen
          python3 -m venv venv
          source venv/bin/activate
          pip install -r requirements.txt

      - name: Build
        run: |
          cd docs
          source venv/bin/activate
          python make_docs.py

      - name: Publish
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./build/docs