name: Docs

on:
  push:
    branches:
      - development
  pull_request:
    branches:
      - development

permissions:
  contents: write

env:
  CPM_SOURCE_CACHE: ${{ github.workspace }}/cpm_modules

jobs:
  build-docs:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive

      - uses: prefix-dev/setup-pixi@v0.9.6
        with:
          pixi-version: v0.68.1
          cache: true
          frozen: true

      - uses: actions/cache@v4
        with:
          path: "**/cpm_modules"
          key: ${{ github.workflow }}-cpm-modules-${{ hashFiles('**/CMakeLists.txt', '**/*.cmake') }}

      - uses: actions/cache@v4
        id: cache-lupnt-data
        with:
          path: data/LuPNT_data
          key: LuPNT_data-${{ vars.LUPNT_DATA_CACHE_DATE }}

      - name: Download LuPNT_data
        if: steps.cache-lupnt-data.outputs.cache-hit != 'true'
        run: |
          mkdir -p data
          curl -L https://bit.ly/LuPNT_data -o LuPNT_data.zip
          unzip -q LuPNT_data.zip
          rm -rf data/LuPNT_data
          mv LuPNT_data data/LuPNT_data
          rm LuPNT_data.zip

      - name: Build docs
        run: pixi run build-docs

      - name: Publish
        if: github.event_name == 'push'
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./build/docs
