name: Ubuntu

on:
  push:
    branches:
      - development
  pull_request:
    branches:
      - development

env:
  CTEST_OUTPUT_ON_FAILURE: 1
  CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
  CPM_SOURCE_CACHE: ${{ github.workspace }}/cpm_modules
  LUPNT_DATA_PATH: ${{ github.workspace }}/LuPNT_data

jobs:
  build-ubuntu:
    runs-on: ubuntu-latest

    steps:
      - name: install dependencies
        run: sudo apt-get install -y libboost-all-dev libomp-dev libhdf5-serial-dev

      - uses: actions/checkout@v4

      - uses: actions/cache@v4
        id: cache-cpm-modules
        with:
          path: "**/cpm_modules"
          key: ${{ github.workflow }}-cpm-modules-${{ hashFiles('**/CMakeLists.txt', '**/*.cmake') }}

      - uses: actions/cache@v4
        id: cache-lupnt-data
        with:
          path: data
          key: LuPNT_data-${{ vars.LUPNT_DATA_CACHE_DATE }}

      - name: download and unzip LuPNT_data
        if: steps.cache-lupnt-data.outputs.cache-hit != 'true'
        run: |
          curl -L https://bit.ly/LuPNT_data -o LuPNT_data.zip
          unzip LuPNT_data.zip
          rm LuPNT_data.zip

      - name: configure
        run: cmake -Stest -Bbuild -DENABLE_TEST_COVERAGE=1 -DCMAKE_BUILD_TYPE=Debug

      - name: build
        run: cmake --build build -j4

      - name: test
        run: |
          cd build
          ctest --build-config Debug

      - name: collect code coverage
        run: bash <(curl -s https://codecov.io/bash) || echo "Codecov did not collect coverage reports"
